### ISSUE TITLE
Auto headers inserted into `headers._list` while not into `headers._dict`

### ISSUE THREAD

**Issue by j178** [encode/httpx#1203]
### Checklist

- [ x ] The bug is reproducible against the latest release and/or `master`.
- [ x ] There are no similar issues or pull requests to fix it yet.

### Describe the bug
`Request.prepare()` insert auto headers into `headers.raw` (ie `headers._list`), but not into the `headers._dict`.
https://github.com/encode/httpx/blob/924fa8c9dc19f3a601db54a384158fef56f07c96/httpx/_models.py#L650-L651

### To reproduce
```python
>>> import httpx
>>> client = httpx.Client()
>>> request = client.build_request("GET", "https://google.com")
>>> requests.headers
Headers({'host': 'google.com', 'user-agent': 'python-httpx/0.14.1', 'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'connection': 'keep-alive'})
>>> "host" in request.headers
False
>>> request.headers.pop("host")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\programs\anaconda3\lib\_collections_abc.py", line 801, in pop
    del self[key]
  File "E:\projects\pycharm\httpx\httpx\_models.py", line 536, in __delitem__
    del self._dict[del_key]
KeyError: b'host'
```

### Environment

- OS: Windows/macOS
- Python version: 3.7.6
- HTTPX version: 0.14.1

**Comment by tomchristie** [comment]
Introduced by #1089.
Resolved and test case'd in #1205.
