### ISSUE TITLE
_get_stream_by_id error

### ISSUE THREAD

**Issue by scaredos** [encode/httpx#1231]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "bot.py", line 328, in search
    await searchIt(ctx, query1)
  File "bot.py", line 90, in searchIt
    xx = await requests.get(str('https://www.imdb.com/title/'+id))
  File "/usr/lib/python3.8/site-packages/http3/client.py", line 305, in get
    return await self.request(
  File "/usr/lib/python3.8/site-packages/http3/client.py", line 541, in request
    response = await self.send(
  File "/usr/lib/python3.8/site-packages/http3/client.py", line 140, in send
    response = await self.send_handling_redirects(
  File "/usr/lib/python3.8/site-packages/http3/client.py", line 177, in send_handling_redirects
    response = await self.dispatch.send(
  File "/usr/lib/python3.8/site-packages/http3/dispatch/connection_pool.py", line 130, in send
    raise exc
  File "/usr/lib/python3.8/site-packages/http3/dispatch/connection_pool.py", line 120, in send
    response = await connection.send(
  File "/usr/lib/python3.8/site-packages/http3/dispatch/connection.py", line 56, in send
    response = await self.h2_connection.send(request, timeout=timeout)
  File "/usr/lib/python3.8/site-packages/http3/dispatch/http2.py", line 52, in send
    status_code, headers = await self.receive_response(stream_id, timeout)
  File "/usr/lib/python3.8/site-packages/http3/dispatch/http2.py", line 126, in receive_response
    event = await self.receive_event(stream_id, timeout)
  File "/usr/lib/python3.8/site-packages/http3/dispatch/http2.py", line 159, in receive_event
    events = self.h2_state.receive_data(data)
  File "/usr/lib/python3.8/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
  File "/usr/lib/python3.8/site-packages/h2/connection.py", line 1486, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
  File "/usr/lib/python3.8/site-packages/h2/connection.py", line 1736, in _receive_window_update_frame
    stream = self._get_stream_by_id(frame.stream_id)
  File "/usr/lib/python3.8/site-packages/h2/connection.py", line 615, in _get_stream_by_id
    raise StreamClosedError(stream_id)
h2.exceptions.StreamClosedError: 1```
When I try to request https://imdb.com/, that's the following error I get. Does anyone know why? I checked https://github.com/encode/httpx/issues/173, I'm running the latest version of h2 and http3.

**Comment by tomchristie** [comment]
Would you be able to follow up with why you've closed this?

Also is anyone else able to replicate this? (I'm on mobile only over the next few days)
