### ISSUE TITLE
HTTPCore exceptions leaking into HTTPX?

### ISSUE THREAD

**Issue by andrewshadura** [encode/httpx#1251]
Sorry for not filing this according to the template, but I’m not sure whether this is something on my side or not, so I thought I would ask before investigating further.
Unless I’m mistaken, HTTPCore exceptions should be mapped to HTTPX ones, but this is what I’m seeing:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Quart-0.13.0-py3.8.egg/quart/app.py", line 1815, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/Quart-0.13.0-py3.8.egg/quart/app.py", line 1837, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/usr/local/lib/python3.8/dist-packages/Quart-0.13.0-py3.8.egg/quart/app.py", line 1077, in handle_user_exception
    raise error
  File "/usr/local/lib/python3.8/dist-packages/Quart-0.13.0-py3.8.egg/quart/app.py", line 1835, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.8/dist-packages/Quart-0.13.0-py3.8.egg/quart/app.py", line 1883, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/local/lib/python3.8/dist-packages/obs_proxy-0-py3.8.egg/obs_proxy/repserver.py", line 119, in putjob
    resp = await client.post(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1374, in post
    return await self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1147, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1168, in send
    response = await self.send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1195, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1232, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1264, in send_single_request
    ) = await transport.request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_async/connection_pool.py", line 152, in request
    response = await connection.request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_async/connection.py", line 78, in request
    return await self.connection.request(method, url, headers, stream, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_async/http11.py", line 56, in request
    await self._send_request_body(stream, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_async/http11.py", line 94, in _send_request_body
    await self._send_event(event, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_async/http11.py", line 106, in _send_event
    await self.socket.write(bytes_to_send, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_backends/asyncio.py", line 146, in write
    return await asyncio.wait_for(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.WriteError: [Errno 32] Broken pipe
```
The code in question is doing this:
```python
async def upload_bytes():
    async for data in request.body:
        yield data

try:
    resp = await client.post(
        uri, params=request.args, data=upload_bytes(), auth=build_auth(), timeout=HTTP_TIMEOUT
    )
except httpx.HTTPError as e:
    return str(e), 500
```

**Comment by tomchristie** [comment]
Thanks for the report. Which version are you using here?

**Comment by andrewshadura** [comment]
Sorry — it’s 0.14.2, but I checked the changelog and there doesn’t appear to be any change in the exception handling between that and 0.14.3 in httpx.

**Comment by tomchristie** [comment]
The traceback lines don't seem to match up with what I'd expect in 0.14.2.

From the traceback details it *looks* like it might actually be version 0.13.3, eg...

```python
File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1232, in send_handling_auth
    response = await self.send_single_request(request, timeout)
File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1264, in send_single_request
    ) = await transport.request(
```

* Line 1232 : https://github.com/encode/httpx/blob/0.13.3/httpx/_client.py#L1232
* Line 1264 : https://github.com/encode/httpx/blob/0.13.3/httpx/_client.py#L1264

In which case it wouldn't surprised me that it's not correctly wrapping up `httpcore` exceptions.

**Comment by andrewshadura** [comment]
Hmm, maybe there's some miscommunication in the team we have here. We were supposed to have 0.14.2, but apparently the upgrade didn't happen everywhere. I'll check up and see.

-- 
Cheers,
  Andrej

**Comment by andrewshadura** [comment]
Thanks for helping and sorry for the false positive; I should have realised this myself. What happened is that another team member was running this with 0.13.3 when he was supposed to be running 0.14.2. I received crash logs from his environment but didn’t re-run it locally since it would be too difficult to reproduce the environment anyway, so I went ahead with reading the code and trying to figure out what’s wrong.

Again, sorry for the noise :slightly_smiling_face:

**Comment by tomchristie** [comment]
👍👍
