### ISSUE TITLE
Avoid SSL verification in AsyncClient()

### ISSUE THREAD

**Issue by baptistapedro** [encode/httpx#1331]
```
async def do_request(urls):
    for u in urls:
        async with httpx.AsyncClient() as client:
            client.verify = False
            client.cert = None
            try:
                r = await client.get(u, timeout=20, allow_redirects=True)
```

```
Traceback (most recent call last):
  File "light.py", line 78, in <module>
    asyncio.run(do_request(urls))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "light.py", line 51, in do_request
    r = await client.get(u, timeout=20, allow_redirects=True)
  File "/home/nasa/.local/lib/python3.8/site-packages/httpx/_client.py", line 1544, in get
    return await self.request(
  File "/home/nasa/.local/lib/python3.8/site-packages/httpx/_client.py", line 1363, in request
    response = await self.send(
  File "/home/nasa/.local/lib/python3.8/site-packages/httpx/_client.py", line 1396, in send
    response = await self._send_handling_auth(
  File "/home/nasa/.local/lib/python3.8/site-packages/httpx/_client.py", line 1434, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/nasa/.local/lib/python3.8/site-packages/httpx/_client.py", line 1466, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/nasa/.local/lib/python3.8/site-packages/httpx/_client.py", line 1498, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nasa/.local/lib/python3.8/site-packages/httpx/_exceptions.py", line 356, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
```

How can I avoid such verifications?

**Comment by baptistapedro** [comment]
I saw this issue -> https://github.com/encode/httpx/issues/475
but when I try to do the SSL setup like on that post I get

```
ssl_config = httpx.SSLConfig()
AttributeError: module 'httpx' has no attribute 'SSLConfig'
```

**Comment by florimondmanca** [comment]
Hi,

You can pass `verify=False` when instantiating the client, and SSL vérification will be bypassed.

Note that this is a client level option only, so one approach you could have is have two separate client instances, and have a fallback policy where you try with SSL verification enabled (default client), and if that fails, try again with SSL verification disabled (no-verify client). Or something along these lines. :)

Thanks!

**Comment by florimondmanca** [comment]
PS: I see you're setting `.verify=False` on the client after it has been instantiated, but I'm not sure this can work at all, and it is not documented. Make sure to pass this option on client unit instead!

**Comment by Jayleelwj** [comment]
try the `pip` command: 
```
pip install python-certifi-win32
```
