### ISSUE TITLE
httpx.ConnectError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1108)

### ISSUE THREAD

**Issue by zhs509** [encode/httpx#1373]
```
import httpx
url = 'https://www.xhssy.com.cn/forum.php?mod=forumdisplay&fid=81&filter=author&orderby=dateline'
resp = httpx.get(url)
print(resp.status_code)
```

```
import requests
url = 'https://www.xhssy.com.cn/forum.php?mod=forumdisplay&fid=81&filter=author&orderby=dateline'
resp = requests.get(url)
print(resp.status_code)
```

**When i use  httpx.get  return exception：httpx.ConnectError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1108)，but  requests.get is ok.**

`Traceback (most recent call last):
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
    yield
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpcore\_sync\connection_pool.py", line 200, in request
    response = connection.request(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpcore\_sync\connection.py", line 87, in request
    self.socket = self._open_socket(timeout)
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpcore\_sync\connection.py", line 108, in _open_socket
    return self.backend.open_tcp_stream(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/python/project/yuqing_tool/httpx_requests.py", line 3, in <module>
    resp = httpx.get(url)
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_api.py", line 181, in get
    return request(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_api.py", line 93, in request
    return client.request(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_client.py", line 733, in request
    return self.send(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_client.py", line 767, in send
    response = self._send_handling_auth(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_client.py", line 805, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\zhs\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1108)`

**Comment by LR1093141031** [comment]
Almost the same issue. Is there any temprate way to deal with?

**Comment by LR1093141031** [comment]
check this. https://www.gitmemory.com/issue/encode/httpx/1189/676036534
by downgrade to 0.13 mine was solved.

**Comment by florimondmanca** [comment]
@zhs509 

* Can you clarify if you're using any proxies here?
* I ran a test of the endpoint you linked to through https://www.ssllabs.com/ssltest/, and it says that the website only supports SSLv2, SSLv3, TLS 1.0 (see [results](https://www.ssllabs.com/ssltest/analyze.html?d=www.xhssy.com.cn)). HTTPX only allows TLS1.2 and up by default. Obviously my first recommendation would be to upgrade the website to a newer TLS protocol if you have control over it. If you don't and you still want to communicate with the server, you'll need to explicitly enable support for those older and insecure versions. For example:

```python
import httpx
import ssl

ssl_context = httpx.create_ssl_context()
ssl_context.options ^= ssl.OP_NO_TLSv1  # Enable TLS 1.0 back
resp = httpx.get(..., verify=ssl_context)
```

It's also possible that "Unsupported protocol" may be linked to incompatible cipher suites between what we enable by default and what is supported by the website (ssltest shows that all cipher suites supported by the websites are "WEAK" at best, so it's very likely we don't support them by default). If so, you can take a look at [`SSLContext.set_ciphers()`](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.set_ciphers). The code where we set default cipher suites using this method is [here](https://github.com/encode/httpx/blob/master/httpx/_config.py#L162).

I'm anticipating the above should help you solve your issues, so I'm closing in advance, but if that's not the case feel free to reach out to the [chat](https://gitter.im/encode/community) if you need some more help.

Cheers!

**Comment by zhs509** [comment]
> @zhs509
> 
> * Can you clarify if you're using any proxies here?
> * I ran a test of the endpoint you linked to through https://www.ssllabs.com/ssltest/, and it says that the website only supports SSLv2, SSLv3, TLS 1.0 (see [results](https://www.ssllabs.com/ssltest/analyze.html?d=www.xhssy.com.cn)). HTTPX only allows TLS1.2 and up by default, as you can see [here](https://github.com/encode/httpx/blob/1bc3b0188a65cfa3f3dc8b85a0ed0e78d437ba5e/httpx/_config.py#L157-L160). Obviously my first recommendation would be to upgrade the website to a newer TLS protocol if you have control over it. If you don't and you still want to communicate with the server, you'll need to explicitly enable support for those older and insecure versions. For example:
> 
> ```python
> import httpx
> import ssl
> 
> ssl_context = httpx.create_ssl_context()
> ssl_context.options ^= ssl.OP_NO_TLSv1  # Enable TLS 1.0 back
> resp = httpx.get(..., verify=ssl_context)
> ```
> 
> It's also possible that "Unsupported protocol" may be linked to incompatible cipher suites between what we enable by default and what is supported by the website (ssltest shows that all cipher suites supported by the websites are "WEAK" at best, so it's very likely we don't support them by default). If so, you can take a look at [`SSLContext.set_ciphers()`](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.set_ciphers). The code where we set default cipher suites using this method is [here](https://github.com/encode/httpx/blob/master/httpx/_config.py#L162).
> 
> I'm anticipating the above should help you solve your issues, so I'm closing in advance, but if that's not the case feel free to reach out to the [chat](https://gitter.im/encode/community) if you need some more help.
> 
> Cheers!

```
import httpx
import ssl

ssl_context = httpx.create_ssl_context()
ssl_context.options ^= ssl.OP_NO_TLSv1  # Enable TLS 1.0 back
resp = httpx.get(..., verify=ssl_context)
```
use this is ok.

**Comment by nyuszika7h** [comment]
I'm seeing this error on httpx 0.22.0 even with a HTTPS proxy that supports TLSv1.3. The proposed workaround does not fix it.

```
❯ openssl s_client -connect hu-001.whiskergalaxy.com:443 </dev/null 2>&1 | grep TLS
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
```

```
❯ python
Python 3.10.4 (main, Apr  4 2022, 14:54:08) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpx
>>> httpx.__version__
'0.22.0'
>>> client = httpx.Client(proxies={"all://": "https://REDACTED:REDACTED@hu-001.whiskergalaxy.com"})
>>> client.get("https://example.com")
Traceback (most recent call last):
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/backends/sync.py", line 52, in start_tls
    sock = ssl_context.wrap_socket(
  File "/home/nyuszika7h/.pyenv/versions/3.10.4/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/nyuszika7h/.pyenv/versions/3.10.4/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/home/nyuszika7h/.pyenv/versions/3.10.4/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/_sync/http_proxy.py", line 283, in handle_request
    stream = stream.start_tls(**kwargs)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/backends/sync.py", line 49, in start_tls
    with map_exceptions(exc_map):
  File "/home/nyuszika7h/.pyenv/versions/3.10.4/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1025, in get
    return self.request(
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/home/nyuszika7h/.pyenv/versions/3.10.4/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:997)
>>>
```
