### ISSUE TITLE
HTTP2 Client parallel requests causes some responses to be ignored with Alexa

### ISSUE THREAD

**Issue by vong0** [encode/httpx#1396]
Hi, so I've been using your httpx.Client with HTTP2 enabled.
```
http.Client(url, http2=True)
```
I've been using this client to communicate with Alexa Voice Service to send audio files and receive a response.
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/manage-http2-connection.html
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/structure-http2-request.html

I've been using this repo as my basis https://github.com/richtier/alexa-voice-service-client
- I have replaced all instances of hyper with httpx. 
- Once I had that done, I was able to send audio files and receive their corresponding response. Everything was working.
- The audio files I was sending were all the same and I got the same responses for each of them which was as expected.

However, I noticed that when I run 2 separate instances of my python script in parallel.
```
terminal 1: python3 main.py
terminal 2: python3 main.py
```

I found out that some of my HTTP2 responses from terminal 1 were empty when terminal 2 was running.
- My python script was using a different account to connect to Alexa
    - Each script was connecting to the same base url but with different authentication credentials
- The python scripts were also run as 2 different processes
- This only happens when I have 2 instances of the same script running. This issues does not occur if I only have 1 client running.
    - Note: responses are empty even when they are run as separate processes

I've managed to also reproduce this issue using the python multiprocessing module
- If the same request is sent in 2 different clients each in their own process at the same time
- the response in the 1st client seems to get dropped

Do you have any idea why this is happening? 
- How is it possible for HTTP2 clients in different processes to affect each other?

**Comment by florimondmanca** [comment]
Hello! Hmm, interesting one.

> I've managed to also reproduce this issue using the python multiprocessing module

That's a helpful pointer. Does it also reproduce if running two requests concurrently using multithreading? (I'm assuming you use our synchronous `httpx.Client`.)

Besides, would you be able to share stripped-down versions of those scripts that reproduce the issue you're seeing? Is it specific to your Alexa service, or does this also reproduce against other HTTP/2 sites? Maybe we can have an HTTP/2 server locally with some heavy-weight endpoints and see if this reproduces…

We need to figure out if A/ we're doing something wrong, B/ the Alexa service in particular is doing wrong, or C/ something else… And working from a minimal reproducible script, and ideally reproducing on a local setup is the best way forward.

**Comment by sethmlarson** [comment]
I wouldn't be surprised if Alexa is handing you back empty responses because it's detecting two HTTP/2 connections from the same host / user-agent / etc.

From HTTP/2 RFC Section 9.1:

> Clients SHOULD NOT open more than one HTTP/2 connection to a given host and port pair, where the host is derived from a URI, a selected alternative service [ALT-SVC], or a configured proxy.

**Comment by vong0** [comment]
> Hello! Hmm, interesting one.
> 
> > I've managed to also reproduce this issue using the python multiprocessing module
> 
> That's a helpful pointer. Does it also reproduce if running two requests concurrently using multithreading? (I'm assuming you use our synchronous `httpx.Client`.)
> 
> Besides, would you be able to share stripped-down versions of those scripts that reproduce the issue you're seeing? Is it specific to your Alexa service, or does this also reproduce against other HTTP/2 sites? Maybe we can have an HTTP/2 server locally with some heavy-weight endpoints and see if this reproduces…
> 
> We need to figure out if A/ we're doing something wrong, B/ the Alexa service in particular is doing wrong, or C/ something else… And working from a minimal reproducible script, and ideally reproducing on a local setup is the best way forward.

When sending requests concurrently using multithreading:
- Responses also do get dropped but the number of responses dropped is significantly less
- I've tested with a threadpoolexecutor of 8 threads and i've noticed that sometimes they get dropped and sometimes they don't
    - NOTE: Alexa can take up to 10 concurrent streams (2 of them are used for something else, so that is why I've been using 8)

However, with multiprocessing (using the multiprocessing module or running the script independently):
- Even with a different account, almost all the responses are getting dropped.

For the stripped-down versions of the scripts.
- There is some setup involved so I probably won't get up to that until sometime next week.

**Comment by vong0** [comment]
> I wouldn't be surprised if Alexa is handing you back empty responses because it's detecting two HTTP/2 connections from the same host / user-agent / etc.
> 
> From HTTP/2 RFC Section 9.1:
> 
> > Clients SHOULD NOT open more than one HTTP/2 connection to a given host and port pair, where the host is derived from a URI, a selected alternative service [ALT-SVC], or a configured proxy.

That could be true. I'm not 100% sure since the Alexa documentation doesn't explicitly say anything about it.

**Comment by vong0** [comment]
Hi, thanks for the wait. 

So I've finally gotten around to uploading the stripped down versions of the code:
- It is available at https://github.com/vong0/alexa-client-python
- Please follow the instructions in the README.md for setup
    - I know the setup is long so bear with me

I've tested on another computer and I've found that the responses are no longer being dropped:
- I'm not too sure why and I haven't been able to reproduce it yet.

But I've run into multiple different issues.
- see the `main_threaded.py` for the issues and ways to reproduce it.

When sending multiple responses simultaneously. I receive 2 different types of exceptions:
- If the `timeout` parameter in the HTTP2 sync client is set to None
    - I receive a `httpx.RemoteProtocolError`
```
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/connection_pool.py", line 219, in request
    method, url, headers=headers, stream=stream, ext=ext
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/connection.py", line 106, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 119, in request
    return h2_stream.request(method, url, headers, stream, ext)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 294, in request
    self.send_body(stream, timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 336, in send_body
    self.stream_id, timeout
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 182, in wait_for_outgoing_flow
    self.receive_events(timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 215, in receive_events
    raise RemoteProtocolError(event)
httpcore.RemoteProtocolError: <ConnectionTerminated error_code:ErrorCodes.COMPRESSION_ERROR, last_stream_id:31, additional_data:485041434b202d20696c6c6567616c20696e6465>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_threaded.py", line 67, in <module>
    path, r, directives = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main_threaded.py", line 37, in send_audio_file
    r = alexa.send_audio_file(client, f)
  File "/mnt/c/Users/matth/Documents/alexa/alexa-client/avs/alexa.py", line 97, in send_audio_file
    r = client.request("POST", "/v20160207/events", files=files, headers=headers)
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 734, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 772, in send
    history=[],
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 809, in _send_handling_auth
    history=history,
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.RemoteProtocolError: <ConnectionTerminated error_code:ErrorCodes.COMPRESSION_ERROR, last_stream_id:31, additional_data:485041434b202d20696c6c6567616c20696e6465
```
- If the `timeout` parameter in the HTTP2 sync client is set to some long period e.g. 3600
    - I receive a `httpx.ReadError`
```
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/connection_pool.py", line 219, in request
    method, url, headers=headers, stream=stream, ext=ext
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/connection.py", line 106, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 119, in request
    return h2_stream.request(method, url, headers, stream, ext)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 297, in request
    status_code, headers = self.receive_response(timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 351, in receive_response
    event = self.connection.wait_for_event(self.stream_id, timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 198, in wait_for_event
    self.receive_events(timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_sync/http2.py", line 205, in receive_events
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/matt/.local/lib/python3.6/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_threaded.py", line 67, in <module>
    path, r, directives = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main_threaded.py", line 37, in send_audio_file
    r = alexa.send_audio_file(client, f)
  File "/mnt/c/Users/matth/Documents/alexa/alexa-client/avs/alexa.py", line 97, in send_audio_file
    r = client.request("POST", "/v20160207/events", files=files, headers=headers)
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 734, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 772, in send
    history=[],
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 809, in _send_handling_auth
    history=history,
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/matt/.local/lib/python3.6/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadError: [Errno 11] Resource temporarily unavailable
```

Any ideas what is causing this? Again, this might be an Alexa issue but I'm not quite sure.

**Comment by florimondmanca** [comment]
I've got no clue off the top of my head for now. The ReadError seems expected — it seems to be mapped from `socket.timeout`. How long does it take to occur; less than an hour I suppose?

I was about to suggest comparing behavior with other HTTP/2 sync clients, but I think HTTPX is one-of-its-kind in that space... :-)

**Comment by vong0** [comment]
> I've got no clue off the top of my head for now. The ReadError seems expected — it seems to be mapped from `socket.timeout`. How long does it take to occur; less than an hour I suppose?
> 
> I was about to suggest comparing behavior with other HTTP/2 sync clients, but I think HTTPX is one-of-its-kind in that space... :-)

The program only runs for about 1min. The read error occurs if I have the timeout set to anything other than None (if if i set it to 1 hour). 

Yea I don't think there are any other HTTPX sync clients available right now. There was the https://github.com/python-hyper/hyper does exist but it hasn't been maintained or updated for 3 years now.

**Comment by tomchristie** [comment]
Similarly to #1410 I'm going to close this off as stale.

@vong0 - If you're still interested in taking a look at this (and if it's still valid, given the large amount of progress that `httpcore` has made since this was opened) then I'll happily reopen and spend some time working through it with you.

Given you were working with two completely independent processes, Seth's take on this seems to me like it might well have been a good one. A good tack for looking into this would likely be to slim thing right down to the point that you could use a couple of different HTTP/2 client implementations and see if you were still able to replicate the behaviour. Using `curl` would be a good candidate.
