### ISSUE TITLE
Proxy CONNECT request timed out when I set the local agent use window10

### ISSUE THREAD

**Issue by tracyqan** [encode/httpx#1412]
when I set the local agent use window10

![20201203102732121](https://user-images.githubusercontent.com/45054429/100955955-79ae7980-3552-11eb-89b7-ddb32bb903ab.png)

use httpx will raise httpx.ConnectTimeout:

```python
httpx.get('https://github.com/')
```

```console
Traceback (most recent call last):
  File "***", line 74, in <module>
    httpx.get('https://github.com/')
  File "E:\Anaconda3\lib\site-packages\httpx\_api.py", line 193, in get
    trust_env=trust_env,
  File "E:\Anaconda3\lib\site-packages\httpx\_api.py", line 104, in request
    allow_redirects=allow_redirects,
  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 734, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 772, in send
    history=[],
  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 809, in _send_handling_auth
    history=history,
  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "E:\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\Anaconda3\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout: _ssl.c:1029: The handshake operation timed out
```

but when I use requests , not raise an error

```python
requests.get('https://github.com/')
```

may I ask why or how I should do?

**Comment by florimondmanca** [comment]
@tracyqan Hey! Just saw this question.

Is that the full traceback? I would have expected another lower-level exception from HTTPCore to be present in the stack (see `from exc` in the `map_exceptions` traceback line). Could you share that here as well? That'd give a better hint at where exactly this handshake failure occurs.

Thanks!

**Comment by tracyqan** [comment]
**Thanks for your reply!
When i run this code.**

```
import httpx
import requests
from loguru import logger
print('============requests===============')
res = requests.get('https://github.com/')
print(res.status_code)
print('============httpx===============')
try:
    httpx.get('https://github.com/')
except:
    logger.exception('Error')
```



**will raise**

```
============requests===============
200
============httpx===============
2020-12-19 18:01:46.840 | ERROR    | __main__:<module>:test.py - Error
Traceback (most recent call last):

  File "E:\Anaconda3\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
    yield

  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
                    │       └ <function Timeout.as_dict at 0x000002AFA3857B70>
                    └ Timeout(timeout=5.0)

  File "E:\Anaconda3\lib\site-packages\httpcore\_sync\http_proxy.py", line 125, in request
    method, url, headers=headers, stream=stream, ext=ext
    │       │            │               │           └ {'timeout': {'connect': 5.0, 'read': 5.0, 'write': 5.0, 'pool': 5.0}}
    │       │            │               └ <httpx._content.PlainByteStream object at 0x000002AFA4284588>
    │       │            └ [(b'Host', b'github.com'), (b'Accept', b'*/*'), (b'Accept-Encoding', b'gzip, deflate'), (b'Connection', b'keep-alive'), (b'Us...
    │       └ (b'https', b'github.com', None, b'/')
    └ b'GET'

  File "E:\Anaconda3\lib\site-packages\httpcore\_sync\http_proxy.py", line 211, in _tunnel_request
    b"CONNECT", connect_url, headers=connect_headers, ext=ext
                │                    │                    └ {'timeout': {'connect': 5.0, 'read': 5.0, 'write': 5.0, 'pool': 5.0}}
                │                    └ [(b'Host', b'github.com:443'), (b'Accept', b'*/*')]
                └ (b'https', b'192.168.35.192', 808, b'github.com:443')

  File "E:\Anaconda3\lib\site-packages\httpcore\_sync\connection.py", line 87, in request
    self.socket = self._open_socket(timeout)
    │    │        │    │            └ {'connect': 5.0, 'read': 5.0, 'write': 5.0, 'pool': 5.0}
    │    │        │    └ <function SyncHTTPConnection._open_socket at 0x000002AFA34DFB70>
    │    │        └ <SyncHTTPConnection http_version=UNKNOWN state=5>
    │    └ None
    └ <SyncHTTPConnection http_version=UNKNOWN state=5>

  File "E:\Anaconda3\lib\site-packages\httpcore\_sync\connection.py", line 113, in _open_socket
    local_address=self.local_address,
                  │    └ None
                  └ <SyncHTTPConnection http_version=UNKNOWN state=5>

  File "E:\Anaconda3\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
           │                     └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
           └ <class 'httpcore._backends.sync.SyncSocketStream'>

  File "E:\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
    │    │   │     │     │      └ <traceback object at 0x000002AFA42853C8>
    │    │   │     │     └ timeout('_ssl.c:1029: The handshake operation timed out')
    │    │   │     └ <class 'socket.timeout'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_exceptions at 0x000002AFA41E2A98>
    └ <contextlib._GeneratorContextManager object at 0x000002AFA42847B8>

  File "E:\Anaconda3\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
          └ <class 'httpcore.ConnectTimeout'>

httpcore.ConnectTimeout: _ssl.c:1029: The handshake operation timed out


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "G:/BND/BankAutomation\test.py", line 9, in <module>
    httpx.get('https://github.com/')
    │     └ <function get at 0x000002AFA386F0D0>
    └ <module 'httpx' from 'E:\\Anaconda3\\lib\\site-packages\\httpx\\__init__.py'>

  File "E:\Anaconda3\lib\site-packages\httpx\_api.py", line 193, in get
    trust_env=trust_env,
              └ True

  File "E:\Anaconda3\lib\site-packages\httpx\_api.py", line 104, in request
    allow_redirects=allow_redirects,
                    └ True

  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 734, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
    │             │                     │                        └ <httpx._config.UnsetType object at 0x000002AFA3855908>
    │             │                     └ True
    │             └ None
    └ <Request('GET', 'https://github.com/')>

  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 772, in send
    history=[],

  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 809, in _send_handling_auth
    history=history,
            └ []

  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
               │    │                    │        └ Timeout(timeout=5.0)
               │    │                    └ <Request('GET', 'https://github.com/')>
               │    └ <function Client._send_single_request at 0x000002AFA3866BF8>
               └ <httpx.Client object at 0x000002AFA4254BE0>

  File "E:\Anaconda3\lib\site-packages\httpx\_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
                    │       └ <function Timeout.as_dict at 0x000002AFA3857B70>
                    └ Timeout(timeout=5.0)

  File "E:\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
    │    │   │     │     │      └ <traceback object at 0x000002AFA42857C8>
    │    │   │     │     └ ConnectTimeout(timeout('_ssl.c:1029: The handshake operation timed out'))
    │    │   │     └ <class 'httpcore.ConnectTimeout'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_exceptions at 0x000002AFA41E2A20>
    └ <contextlib._GeneratorContextManager object at 0x000002AFA4259240>

  File "E:\Anaconda3\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
          │          │          └ {'request': <Request('GET', 'https://github.com/')>}
          │          └ '_ssl.c:1029: The handshake operation timed out'
          └ <class 'httpx.ConnectTimeout'>

httpx.ConnectTimeout: _ssl.c:1029: The handshake operation timed out

Process finished with exit code 0

```

**Comment by florimondmanca** [comment]
@tracyqan Hey, thanks! That loguru tool is very helpful. :)

From that traceback it seems you've set your proxy URL as an HTTPS proxy (the CONNECT request was made to `https://<ip>:808`).

Is that what you meant? Right now we don't actually have support for HTTPS proxies, but judging from the "SSL timed out" error it might actually be that your proxy is a regular HTTP proxy.

I'd suggest trying replacing the proxy URL with the http:// equivalent, rather than https://, and see how that goes?

**Comment by tracyqan** [comment]
Okey， It work well with `proxies={'http': 'http://192.168.35.192:808'}`.

I look forward to supporting HTTPS!!!

**Comment by florimondmanca** [comment]
@tracyqan You can also do:

```python
proxies='http://192.168.35.192:808'
```

And in that case you'll _also_ be able to make HTTPS requests through your proxy. (The mechanism used in this case is called "HTTP tunneling", some more details in the docs here: https://www.python-httpx.org/advanced/#forward-vs-tunnel)

It's a common mistake to set an HTTPS proxy URL on the "https" key in `proxies`, we documented it in a "gotcha" here: https://www.python-httpx.org/advanced/#example

Okay, looks like this is resolved then. :)
