### ISSUE TITLE
Invalid request URL using AsyncClient + HTTP/2 + FORWARD_ONLY Proxy

### ISSUE THREAD

**Issue by ech0-py** [encode/httpx#1428]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
The httpx.AsyncClient with HTTP/2 enabled and using FORWARD_ONLY Proxy builds incorrect request URL: the proxy URL concatenates with requested URL

### To reproduce
Pre-conditions:
- proxy server is configured to work in forward mode with enabled ssl, alpn, http/2
- destination server: simple aiohttp web server that gives valid resposes on any valid requests

The client's code:
```
import httpx

proxy_https4 = httpx.Proxy(
    url=f"https://10.9.0.1:4443",  # proxy addr:port
    mode='FORWARD_ONLY')

client = httpx.AsyncClient(
    proxies=proxy_https4,
    verify=False, 
    http2=True)

r = await client.get("https://some-domain.com/handler2")
print('>>>> r.text:', r.text)
await client.aclose()  # don't want to use context manager
```

### Expected behavior
Request passes through proxy-server correctly and 200 response from destination server is given back

### Actual behavior
Request passes through proxy-server but destination server returns 400 because it cannot handle the request due to broken url

### Debugging material
stdout log:
```
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_verify_locations cafile=/home/myuser/venv_37_111/lib/python3.7/site-packages/certifi/cacert.pem
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_verify_locations cafile=/home/myuser/venv_37_111/lib/python3.7/site-packages/certifi/cacert.pem
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=False cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=False cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_verify_locations cafile=/home/myuser/venv_37_111/lib/python3.7/site-packages/certifi/cacert.pem
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_verify_locations cafile=/home/myuser/venv_37_111/lib/python3.7/site-packages/certifi/cacert.pem
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=False cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=False cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=True cert=None trust_env=None http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_verify_locations cafile=/home/myuser/venv_37_111/lib/python3.7/site-packages/certifi/cacert.pem
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=False cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpx._config - load_ssl_context verify=False cert=None trust_env=True http2=False
TRACE [2020-12-14 10:03:30] httpcore._async.http_proxy - forward_request proxy_origin=(b'https', b'10.9.0.1', 4443) proxy_headers=[] method=b'GET' url=(b'https', b'some-domain.com', None, b'/handler2')
TRACE [2020-12-14 10:03:30] httpcore._async.connection_pool - adding connection to pool=<AsyncHTTPConnection http_version=UNKNOWN state=0>
TRACE [2020-12-14 10:03:30] httpcore._async.connection - open_socket origin=(b'https', b'10.9.0.1', 4443) timeout={'connect': 5.0, 'read': 5.0, 'write': 5.0, 'pool': 5.0}
TRACE [2020-12-14 10:03:30] httpcore._async.connection - create_connection socket=<httpcore._backends.asyncio.SocketStream object at 0x7fa97ce219d0> http_version='HTTP/2'
TRACE [2020-12-14 10:03:30] httpcore._async.connection - connection.arequest method=b'GET' url=(b'https', b'10.9.0.1', 4443, b'https://some-domain.com/handler2') headers=[(b'Host', b'some-domain.com'), (b'Accept', b'*/*'), (b'Accept-Encoding', b'gzip, deflate'), (b'Connection', b'keep-alive'), (b'User-Agent', b'python-httpx/0.16.1')]
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - initiate_connection=<AsyncHTTP2Connection state=2>
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - send_headers stream_id=1 headers=[(b':method', b'GET'), (b':authority', b'10.9.0.1:4443'), (b':scheme', b'https'), (b':path', b'https://some-domain.com/handler2'), (b'accept', b'*/*'), (b'accept-encoding', b'gzip, deflate'), (b'connection', b'keep-alive'), (b'user-agent', b'python-httpx/0.16.1')]
10:03:30.690 hpack.hpack DEBUG: HPACK encoding <generator object _check_path_header.<locals>.inner at 0x7fa97ce8c8d0>
10:03:30.691 hpack.hpack DEBUG: Adding (b':method', b'GET') to the header table
10:03:30.692 hpack.hpack DEBUG: Encoding 2 with 7 bits
10:03:30.692 hpack.hpack DEBUG: Adding (b':authority', b'10.9.0.1:4443') to the header table
10:03:30.692 hpack.hpack DEBUG: Encoding 1 with 6 bits
10:03:30.693 hpack.hpack DEBUG: Encoding 10 with 7 bits
10:03:30.693 hpack.hpack DEBUG: Adding (b':scheme', b'https') to the header table
10:03:30.694 hpack.hpack DEBUG: Encoding 7 with 7 bits
10:03:30.694 hpack.hpack DEBUG: Adding (b':path', b'https://some-domain.com/handler2') to the header table
10:03:30.694 hpack.hpack DEBUG: Encoding 4 with 6 bits
10:03:30.695 hpack.hpack DEBUG: Encoding 17 with 7 bits
10:03:30.695 hpack.hpack DEBUG: Adding (b'accept', b'*/*') to the header table
10:03:30.696 hpack.hpack DEBUG: Encoding 19 with 6 bits
10:03:30.696 hpack.hpack DEBUG: Encoding 3 with 7 bits
10:03:30.696 hpack.hpack DEBUG: Adding (b'accept-encoding', b'gzip, deflate') to the header table
10:03:30.696 hpack.hpack DEBUG: Encoding 16 with 7 bits
10:03:30.697 hpack.hpack DEBUG: Adding (b'user-agent', b'python-httpx/0.16.1') to the header table
10:03:30.697 hpack.hpack DEBUG: Encoding 58 with 6 bits
10:03:30.698 hpack.hpack DEBUG: Encoding 14 with 7 bits
10:03:30.698 hpack.hpack DEBUG: Encoded header block to b'\x82A\x8a\x08\x17}p.\x1b\x8d4\xd3?\x87D\x91\x9d)\xad\x17\x18b\xbfI\x9c\xf5.{&`\xa4\x9c\xe2S\x83\xf9c\xe7\x90z\x8e\xaf\xd2g=KN\x94\xd7\xe5\x80.\x17\x17\x0f'
10:03:30.700 aiohttp.server ERROR: Error handling request
Traceback (most recent call last):
  File "/home/myuser/venv_37_111/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
  File "aiohttp/_http_parser.pyx", line 630, in aiohttp._http_parser.cb_on_header_field
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpRequestParser._on_status_complete
  File "aiohttp/_http_parser.pyx", line 844, in aiohttp._http_parser._parse_url
aiohttp.http_exceptions.InvalidURLError: 400, message="invalid url b'https://10.9.0.1:4443https://some-domain.com/handler2'"
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - receive_event stream_id=0 event=<RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=100)}>
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - receive_event stream_id=0 event=<SettingsAcknowledged changed_settings:{}>
10:03:30.704 hpack.hpack DEBUG: Decoding b'\x8c_\x19text/plain; charset=utf-8\\\x0260a\x1dMon, 14 Dec 2020 17:03:30 GMTv\x18Python/3.7 aiohttp/3.6.2'
10:03:30.704 hpack.hpack DEBUG: Decoded 12, consumed 1 bytes
10:03:30.705 hpack.hpack DEBUG: Decoded (b':status', b'400'), consumed 1
10:03:30.705 hpack.hpack DEBUG: Decoded 31, consumed 1 bytes
10:03:30.705 hpack.hpack DEBUG: Decoded 25, consumed 1 bytes
10:03:30.706 hpack.hpack DEBUG: Decoded (b'content-type', <memory at 0x7fa97ce0b120>), total consumed 27 bytes, indexed True
10:03:30.706 hpack.hpack DEBUG: Decoded 28, consumed 1 bytes
10:03:30.706 hpack.hpack DEBUG: Decoded 2, consumed 1 bytes
10:03:30.707 hpack.hpack DEBUG: Decoded (b'content-length', <memory at 0x7fa97ce0b1f0>), total consumed 4 bytes, indexed True
10:03:30.707 hpack.hpack DEBUG: Decoded 33, consumed 1 bytes
10:03:30.707 hpack.hpack DEBUG: Decoded 29, consumed 1 bytes
10:03:30.708 hpack.hpack DEBUG: Decoded (b'date', <memory at 0x7fa97ce0b2c0>), total consumed 31 bytes, indexed True
10:03:30.708 hpack.hpack DEBUG: Decoded 54, consumed 1 bytes
10:03:30.708 hpack.hpack DEBUG: Decoded 24, consumed 1 bytes
10:03:30.709 hpack.hpack DEBUG: Decoded (b'server', <memory at 0x7fa97ce0b390>), total consumed 26 bytes, indexed True
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - receive_event stream_id=1 event=<ResponseReceived stream_id:1, headers:[(b':status', b'400'), (b'content-type', b'text/plain; charset=utf-8'), (b'content-length', b'60'), (b'date', b'Mon, 14 Dec 2020 17:03:30 GMT'), (b'server', b'Python/3.7 aiohttp/3.6.2')]>
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - receive_event stream_id=1 event=<DataReceived stream_id:1, flow_controlled_length:60, data:696e76616c69642075726c20622768747470733a>
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - receive_event stream_id=1 event=<DataReceived stream_id:1, flow_controlled_length:0, data:>
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - receive_event stream_id=1 event=<StreamEnded stream_id:1>
DEBUG [2020-12-14 10:03:30] httpx._client - HTTP Request: GET https://some-domain.com/handler2 "HTTP/2 400 Bad Request"
10:03:30.712 httpx._client DEBUG: HTTP Request: GET https://some-domain.com/handler2 "HTTP/2 400 Bad Request"
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - close_stream stream_id=1

>>>> r.text: invalid url b'https://10.9.0.1:4443https://some-domain.com/handler2'

TRACE [2020-12-14 10:03:30] httpcore._async.connection_pool - removing connection from pool=<AsyncHTTPConnection http_version=HTTP/2 state=4>
TRACE [2020-12-14 10:03:30] httpcore._async.http2 - close_connection=<AsyncHTTP2Connection state=4>
```
Proxy server access log (shows the incorrect url and 400 status code from server, same as log above)
```
[14/Dec/2020:10:03:30.698] https-proxy~ proxies_out/10.9.0.1:9001 0/0/0/3/3 400 224 - - ---- 1/1/0/0/0 0/0 "GET https://10.9.0.1:4443https://some-domain.com/handler2 HTTP/2.0"
```

### Environment

- OS: Ubuntu 18.04.2 LTS
- Python version: 3.7.5
- HTTPX version: 0.16.1 (httpcore==0.12.2) both are installed from PyPi
- Async environment: asyncio
- HTTP proxy: yes
- Custom certificates: verify=False

### Additional context
As you can see from log: aiohttp destination webserver was unable to parse the request url and returned an error
Actually the problem [starts here](https://github.com/encode/httpcore/blob/0.12.2/httpcore/_async/http_proxy.py#L162), URL becomes a tuple of four, e.g. `(b'https', b'10.9.0.1', b'4443', b'https://some-domain.com/handler2')` and when it's being unpacked by http2 [here](https://github.com/encode/httpcore/blob/0.12.2/httpcore/_async/http2.py#L315) we're getting wrong `:authority: 10.9.0.1:4443` and `:path: https://some-domain.com/handler` headers, when expecting are: `:authority: some-domain.com`, `:path:  /handler` (connection is already established so using proxy-host/port here is a mistake)

**Comment by ex3me0** [comment]
A little update: the latest master branches of httpx/httpcore have the almost same issue, but URL concatenates differently:
```
[14/Dec/2020:12:45:21.157] https-proxy~ proxies_out/10.9.0.1:9001 0/0/0/3/3 400 221 - - ---- 1/1/0/0/0 0/0 "GET https://python.orghttps://python.org/echo2 HTTP/2.0"
```

**Comment by ex3me0** [comment]
Dirty workaround here (please don't consider this as a fix proposal, it "fixes" only the described issue):
```
from httpcore._async.http2 import AsyncHTTP2Stream

async def custom_send_headers(
    self,
    method: bytes,
    url,
    headers,
    has_body: bool,
    timeout,
) -> None:
    scheme, hostname, port, path = url
    default_port = {b"http": 80, b"https": 443}.get(scheme)
    if port is None or port == default_port:
        authority = hostname
    else:
        authority = b"%s:%d" % (hostname, port)

    # ----------------- added -------------------
    if path.startswith(b'http'):
        from httpx._models import URL as URLM
        target_url = URLM(path.decode())
        authority = target_url.netloc
        if target_url.port:
            authority = f'{authority}:{target_url.port}'
        authority = authority.encode()
        path = target_url.path.encode()
    # ----------------- added END -------------------

    headers = [
        (b":method", method),
        (b":authority", authority),
        (b":scheme", scheme),
        (b":path", path),
    ] + [(k, v) for k, v in headers if k not in (b"host", b"transfer-encoding")]
    print('>>>> send_headers!!!!:', headers)
    end_stream = not has_body

    await self.connection.send_headers(self.stream_id, headers, end_stream, timeout)

AsyncHTTP2Stream.send_headers = custom_send_headers
```

**Comment by florimondmanca** [comment]
@ech0-py Hey!

Thanks for opening this with some much detail.

The "proxy forwarding" code lives here, in case you or anyone else stumbing upon this issue would like to take a closer look at what sort of URL wizardry might be happening:

https://github.com/encode/httpcore/blob/cf45ea73aff56addaac12aa9a9f0cc01adf9c9b1/httpcore/_async/http_proxy.py#L128-L173

Let's perhaps avoid the "let's all put :+1: on the issue" thing — if this is something people are encountering and considering as problematic to them then by all means, any brainpower into figuring out what's happening is super welcome. :-) Or consider sponsoring… (which doesn't come to me personally, but to Tom and the Encode org as a whole) https://github.com/sponsors/encode

**Comment by ech0-py** [comment]
@florimondmanca if you don't mind I'll try to show some weird things from my perspective. 
Also please consider that I'll be using 0.12.2 tag in explanations.
So lets say we're using a proxy instance defined in such way:
```python
httpx.Proxy(
        url='https://10.10.0.1:443',
        mode='FORWARD_ONLY')
```
and destination url looks like:
```python
'https://python.org:443/echo'
```
The [_forward_request method ](https://github.com/encode/httpcore/blob/0.12.2/httpcore/_async/http_proxy.py#L128-L173) mentioned above establishes a connection using `self.proxy_origin` that contains a such tuple `(b'https', b'10.10.0.1', 443)`
```python
        origin = self.proxy_origin  # (b'https', b'10.10.0.1', 443)
        connection = await self._get_connection_from_pool(origin)

        if connection is None:
            connection = AsyncHTTPConnection(
                origin=origin, http2=self._http2, ssl_context=self._ssl_context
            )
            await self._add_to_pool(connection, timeout)
```
Now connection with proxy is established, but the method make the strange things on the next lines:
```python
        scheme, host, port, path = url  # on this line url as is expected (b'https', b'python.org', 443, b'/echo')
        if port is None:
            target = b"%b://%b%b" % (scheme, host, path)
        else:
            target = b"%b://%b:%d%b" % (scheme, host, port, path)

        url = self.proxy_origin + (target,)  # here the url becomes wrong in my opinion (b'https', b'10.10.0.1', 443, b'https://python.org:443/echo')
```
Why did the url changed? I assume that it's a some kind of "workaround" to pass an [assert of AsyncHTTPConnection's `arequest` method](https://github.com/encode/httpcore/blob/0.12.2/httpcore/_async/connection.py#L83) that will be triggered on the next line of our `_forward_request` method:
```python
        (status_code, headers, stream, ext) = await connection.arequest(
            method, url, headers=headers, stream=stream, ext=ext
        )
```
The mentioned assert expects that requested url should match the server with which connection was established before (see comment), **but it's wrong expectation/behaviour in case of "forwarding"**
```python
assert url_to_origin(url) == self.origin  # (b'https', b'10.10.0.1', 443, b'https://python.org:443/echo')[:3]  == (b'https', b'10.10.0.1', 443)
```

**Comment by florimondmanca** [comment]
@ech0-py Actually, this "use the full target URL as path" is expected when doing proxy forwarding.

See: https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers

> Web proxies forward HTTP requests. The request from the client is the same as a regular HTTP request except **the full URL is passed**, instead of just the path.
> ```
> GET https://en.wikipedia.org/wiki/Proxy_server HTTP/1.1
> Proxy-Authorization: Basic encoded-credentials
> Accept: text/html
> ```

So the _concept_ of doing this isn't wrong — it's what we're aiming at. However it might be that the execution of it might need to be tweaked?

By the way, does it reproduce _without_ `http2=True`? That way, we can further narrow down whether this is at the HTTP/2 connection level, or higher.

**Comment by florimondmanca** [comment]
@ech0-py Hi, I'm closing this issue off for now because it's more obvious now that we basically need to take a closer and proper look at supporting HTTPS proxies. I've logged #1434. We can still discuss your setup here but I'm closing this for housekeeping so we have a single "HTTPS proxies support" issue to track. Thank you!
