### ISSUE TITLE
Error messaging when using relative URLs w/o `base_url` set could be improved

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1438]
### Overview

When using a `Client` or `AsyncClient` without a `base_url`, calling a relative URL such as `.request("GET", "/")` typically results in unhelpful error messages.

Users are most likely to bump into this when using HTTPX as a test client (calling through a WSGI or ASGI web app), since in that case it's not really expected that a base URL would be necessary at all (since the app is not a remote service that needs DNS addressing etc).

It also applies when requesting through the network, but I'd argue it's less of a problem there.

The issues are:

* We get a different exception when requesting a live host vs a web app (`httpx.UnsupportedProtocol` vs `ValueError`). If both cases fail, it should be with the same exception that says "you're using a relative URL, but no base_url was specified".
* For ASGI and WSGI apps, the problem seems to lie within the cookie building code.
* For live hosts, the URL is detected as invalid scheme. It's possible that if we didn't do this validation, then we'd hit the same error than for ASGI and WSGI apps.

### To reproduce

* Live host:

```pycon
>>> import httpx
>>> client = httpx.Client()
>>> response = client.get("/")
...
httpx.UnsupportedProtocol: Unsupported URL protocol ''
```

<details>
<summary>Click for full traceback</summary>

```console
Traceback (most recent call last):
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_exceptions.py", line 339, in map_exceptions
    yield
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 854, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 173, in request
    raise UnsupportedProtocol(f"Unsupported URL protocol {scheme!r}")
httpcore.UnsupportedProtocol: Unsupported URL protocol ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 900, in get
    return self.request(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 721, in request
    return self.send(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 753, in send
    response = self._send_handling_auth(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 791, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 823, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 854, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_exceptions.py", line 356, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.UnsupportedProtocol: Unsupported URL protocol ''
```

</details>

* WSGI app: we get an error coming from `urllib` when building cookies.

```pycon
>>> import httpx
>>> from flask import Flask
>>> app = Flask()
>>> client = httpx.Client(app=app)  # No `base_url`
>>> response = client.get("/")
...
ValueError: unknown url type: ''
```

<details>
<summary>Click for full traceback</summary>

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 900, in get
    return self.request(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 721, in request
    return self.send(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 753, in send
    response = self._send_handling_auth(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 791, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 823, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 876, in _send_single_request
    self.cookies.extract_cookies(response)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_models.py", line 1321, in extract_cookies
    urllib_request = self._CookieCompatRequest(response.request)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_models.py", line 1445, in __init__
    super().__init__(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```

</details>

* ASGI: same error coming from building cookies:

```pycon
$ python -m asyncio
>>> import httpx
>>> from starlette.applications import Starlette
>>> app = Starlette()
>>> client = httpx.AsyncClient(app=app)  # No `base_url`
>>> response = await client.get("/")
...
ValueError: unknown url type: ''
```

<details>
<summary>Click for full traceback</summary>

```console
Traceback (most recent call last):
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 1546, in get
    return await self.request(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 1364, in request
    response = await self.send(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 1397, in send
    response = await self._send_handling_auth(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 1435, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 1467, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_client.py", line 1522, in _send_single_request
    self.cookies.extract_cookies(response)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_models.py", line 1321, in extract_cookies
    urllib_request = self._CookieCompatRequest(response.request)
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/site-packages/httpx/_models.py", line 1445, in __init__
    super().__init__(
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```

</details>

### Additional context

Prompted by https://github.com/encode/uvicorn/pull/918#issue-545817812 cc @euri10:

> If I had only one slight ux critic it would be that if you forget to pass a `base_url` to the AsyncClient then you get a not very helpful urllib error.
> This is only by experience I remembered that I had to pass it to test directly the asgi app, but I think it's not obvious if you dont know.

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../venv/lib/python3.8/site-packages/httpx/_client.py:1548: in get
    return await self.request(
../../venv/lib/python3.8/site-packages/httpx/_client.py:1371: in request
    response = await self.send(
../../venv/lib/python3.8/site-packages/httpx/_client.py:1406: in send
    response = await self._send_handling_auth(
../../venv/lib/python3.8/site-packages/httpx/_client.py:1444: in _send_handling_auth
    response = await self._send_handling_redirects(
../../venv/lib/python3.8/site-packages/httpx/_client.py:1476: in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
../../venv/lib/python3.8/site-packages/httpx/_client.py:1524: in _send_single_request
    self.cookies.extract_cookies(response)
../../venv/lib/python3.8/site-packages/httpx/_models.py:1329: in extract_cookies
    urllib_request = self._CookieCompatRequest(response.request)
../../venv/lib/python3.8/site-packages/httpx/_models.py:1453: in __init__
    super().__init__(
/home/lotso/.asdf/installs/python/3.8.6/lib/python3.8/urllib/request.py:328: in __init__
    self.full_url = url
/home/lotso/.asdf/installs/python/3.8.6/lib/python3.8/urllib/request.py:354: in full_url
    self._parse()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <httpx._models.Cookies._CookieCompatRequest object at 0x7f4fa4d2b370>

    def _parse(self):
        self.type, rest = _splittype(self._full_url)
        if self.type is None:
>           raise ValueError("unknown url type: %r" % self.full_url)
E           ValueError: unknown url type: ''

/home/lotso/.asdf/installs/python/3.8.6/lib/python3.8/urllib/request.py:383: ValueError
```

**Comment by florimondmanca** [comment]
After digging a bit into it, I think there's unfortunately not much we can do without introducing a whole other range of odd edge cases.

For example, we could switch from `base_url=""` to `base_url=None` in clients, and raise an exception when trying to `_merge_url` from a relative URL while `base_url` is `None`. That would need modifying this code with an extra `if base_url is None` in the `if merge_url.is_relative_url` branch:

https://github.com/encode/httpx/blob/86964054d60da7796c65e501ba021440b14cc36c/httpx/_client.py#L321-L332

Then the behavior would come down to how `URL.is_relative_url` behaves. There are weird edge cases involved, that sometimes come from the `rfc3986` library itself:

```python
>>> import httpx
>>> httpx.URL("://example.org").is_relative_url
True
>>> httpx.URL("invalid://").is_relative_url
True
```

And so, requesting any of these odd-formed URLs would result in a "but you haven't set a `base_url`!" error, which would arguably be even more confusing than the error we get currently when not setting a `base_url`.

Alternatively, we could consider special-casing `app`, and say "set the `base_url` to `http://testserver` if `app` is passed without a `base_url` set". But that feels odd too. If we set that default then it makes it less obvious to people that it comes from `base_url`, so they could treat that as a given and start relying on it, rather than as something they should be setting explicitly.

So… I'm going to close this as "won't fix" for now, but happy to read more thoughts.

**Comment by euri10** [comment]
> So… I'm going to close this as "won't fix" for now, but happy to read more thoughts.

I dont know enough of httpx internals to have an idea, but to me the existence of that issue and the ability for users facing the "error" to google it will probably be enough.
