### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by Sweety133** [encode/httpx#1452]
### Checklist

- [ ] The bug is reproducible against the latest release and/or `master`.
- [ ] There are no similar issues or pull requests to fix it yet.

### Code

def main():
    auth_login = 'test1'
    auth_password = 'test2'
    proxy_headers = {
        "Authorization": generate_basic_header(auth_login, auth_password),
        "Client": 'CLIENT_HERE',
        "Connection": 'keep-alive',
        "Server-Name": 'httpbin.org',
        "Host": 'IP_HERE',
        "Secure": '1',
        "HTTP2": '1',
    }
    proxy_url = 'http://IP:PORT'
    proxy_mode = 'TUNNEL_ONLY'
    timeout = Timeout(read=10, connect=5, timeout=5)
    proxy = Proxy(url=proxy_url, headers=proxy_headers, mode=proxy_mode)
    with Client(http2=True, verify=False, proxies=proxy, timeout=timeout) as client:
        request_url = 'https://httpbin.org/get'
        r = client.get(url=request_url)
        print(r.text)

### Traceback
Traceback (most recent call last):
  File "C:/Users/Test/Desktop/Engine/tests/tls-tunneling.py", line 53, in <module>
    main()
  File "C:/Users/Test/Desktop/Engine/tests/tls-tunneling.py", line 48, in main
    r = client.get(url=request_url)
  File "C:\Users\Test\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 907, in get
    return self.request(
  File "C:\Users\Test\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 733, in request
    return self.send(
  File "C:\Users\Test\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 767, in send
    response = self._send_handling_auth(
  File "C:\Users\Test\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 805, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\Test\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\Users\Test\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "C:\Program Files\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Test\AppData\Roaming\Python\Python38\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ProxyError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)

### Environment

- OS: Windows 10
- Python version: Python 3.8.1
- HTTPX version: 0.16.1
- HTTP proxy: Yes
- Custom certificates: No

Im use my HTTP proxy for custom TLS, i have a problems with TUNNEL_ONLY

**Comment by florimondmanca** [comment]
@Sweety133 Hi,

In my mind there are two possibilities, that basically depend on what we do when using TUNNEL_ONLY with an http:// proxy URL.

* If we connect via HTTP, then it's possible your proxy is in fact an HTTPS one, and we don't support that for now (see related issue).
* If we connect via HTTPS (I don't think that's the case!), then you might want to try dropping TUNNEL_ONLY so HTTPX uses the default.

**Comment by Sweety133** [comment]
My Tunnel support HTTP 2.0, TLS 1.1/1.2/1.3
My Tunnel its HTTP PROXY  SERVER
I have same error without HTTP 2.0

**Comment by tomchristie** [comment]
I'd like to take a look before we consider if this needs closing.

**Comment by tomchristie** [comment]
Let's treat this as stale - we can have another look if it gets bought up by anyone again.
