### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by AmericanY** [encode/httpx#1558]
Valid Response:

```
import requests
with requests.Session() as req:
    req.auth = authdata
    req.headers.update({
        'x-amz-access-token': access
    })

    r = req.get(
        'https://sellingpartnerapi-na.amazon.com/orders/v0/orders/', params=params)
    print(r)
```

Execption AttributeError: 'URL' object has no attribute 'decode'

```
import httpx
async with httpx.AsyncClient(timeout=None) as client:
    client.auth = authdata
    client.headers.update({
        'x-amz-access-token': access
    })
    r = await client.get('https://sellingpartnerapi-na.amazon.com/orders/v0/orders/', params=params)
    print(r)
```

Full Exception:

```
Traceback (most recent call last):
  File "c:\Users\AmericaN\Desktop\Lab\code.py", line 60, in <module>
    trio.run(main)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\trio\_core\_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "c:\Users\AmericaN\Desktop\Lab\code.py", line 56, in main
    await get_orders(authdata, await get_token())
  File "c:\Users\AmericaN\Desktop\Lab\code.py", line 49, in get_orders
    r = await client.get('https://sellingpartnerapi-na.amazon.com/orders/v0/orders/', params=params)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_client.py", line 1539, in get
    return await self.request(
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_client.py", line 1361, in request
    response = await self.send(
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_client.py", line 1396, in send
    response = await self._send_handling_auth(
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_client.py", line 1428, in _send_handling_auth       
    request = await auth_flow.__anext__()
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_auth.py", line 92, in async_auth_flow
    request = next(flow)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_auth.py", line 115, in auth_flow
    yield self._func(request)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\requests_auth_aws_sigv4\__init__.py", line 109, in __call__
    p = urlparse(r.url)
  File "C:\Program Files\Python39\lib\urllib\parse.py", line 389, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "C:\Program Files\Python39\lib\urllib\parse.py", line 125, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "C:\Program Files\Python39\lib\urllib\parse.py", line 109, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "C:\Program Files\Python39\lib\urllib\parse.py", line 109, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'URL' object has no attribute 'decode'
```

**Comment by florimondmanca** [comment]
Heya,

Seems like you're trying to use `requests_auth_aws_sigv4` with HTTPX, but that won't work. In this particular instance you get an error because Requests' and HTTPX's URL objects are different, but even if they were the same the Auth interfaces are different too.

It could be a good opportunity for you to look into a repackaging of that package for HTTPX, or for us to discuss if there's an easy shim we could provide for Requests style Auth classes. There are many Auth packages for Requests and I assume right now them not being available for HTTPX is a blocker for folks, until the ecosystem expands. Either way we can treat that as a separate discussion.

Thanks

**Comment by AmericanY** [comment]
@florimondmanca sad news for me :( as i love to use `httpx` until then, i have to switch to requests as for now.

**Comment by tomchristie** [comment]
Hi @AmericanY, we'd like to be able to support you using `httpx` in the future.
If you'd like to help us do that too, here's a good opportunity...

You *could* [open an "ideas" discussion](https://github.com/encode/httpx/discussions/categories/ideas) suggesting that an AWS SigV4 package for HTTPX would be helpful. It's likely to be helpful if you're able to link to the package & describe what kind of things would be enabled, if there was an HTTPX auth package offering that support.

**Comment by tomchristie** [comment]
Have raised a related discussion on [the possible merits of stricter type checking and better error messaging.](https://github.com/encode/httpx/discussions/1559)

**Comment by Colin-b** [comment]
@AmericanY you should be able to use [httpx-auth](https://pypi.org/project/httpx-auth/) to do so [as described in documentation](https://github.com/Colin-b/httpx_auth#aws-signature-v4)

**Comment by tomchristie** [comment]
@Colin-b - That looks *fantastic*. I don't see it linked to from the ["third party packages"](https://www.python-httpx.org/third-party-packages/) docs. D'ya want to take on a pull request adding it in, perhaps?

**Comment by AmericanY** [comment]
@Colin-b Thanks a lot. you saved my life :)
