### ISSUE TITLE
python3.8/site-packages/httpcore/_backends/anyio.py:198: RuntimeWarning: coroutine 'current_time' was never awaited   return float(anyio.current_time())

### ISSUE THREAD

**Issue by yangkaipeng** [encode/httpx#1768]
when I use the version 0.18.0+, there will be an issue described with "python3.8/site-packages/httpcore/_backends/anyio.py:198: RuntimeWarning: coroutine 'current_time' was never awaited return float(anyio.current_time())" .  I just code it with python-asyncio.  When I update my httpx version on 0.17.1, it is been resovled. SO I think it may be an issue about 0.18.0+

**Comment by tomchristie** [comment]
Thanks for the report!

Could you include a complete traceback for this please?
What's the minimum amount of code you can demonstrate that reproduces the issue?

**Comment by yangkaipeng** [comment]
I am sorry that I can't reappear this issue now. But I will paste my code here next time for you . Thank you very much

**Comment by pltnk** [comment]
Stumbled upon the same issue just now.

**Comment by pltnk** [comment]
Stumbled upon the same issue just now while trying to send requests from Python console using HTTPX 0.18.2.

```
/opt/anaconda3/bin/python /snap/pycharm-professional/248/plugins/python/helpers/pydev/pydevconsole.py --mode=client --port=39383
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/pltnk/GitHub/toptracksbot'])
Python 3.8.10 (default, Jun  4 2021, 15:09:15) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.22.0
Python 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0] on linux
```

Here is the code:
```
import httpx
async with httpx.AsyncClient() as client:
    res = await client.get("http://example.com")
```

And traceback:
```
/opt/anaconda3/lib/python3.8/site-packages/httpcore/_backends/anyio.py:198: RuntimeWarning: coroutine 'current_time' was never awaited
  return float(anyio.current_time())
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3435, in run_code
    await eval(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-74e0c15e1218>", line 2, in <module>
    res = await client.get("http://example.com")
  File "/opt/anaconda3/lib/python3.8/site-packages/httpx/_client.py", line 1722, in get
    return await self.request(
  File "/opt/anaconda3/lib/python3.8/site-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/opt/anaconda3/lib/python3.8/site-packages/httpx/_client.py", line 1568, in send
    response = await self._send_handling_auth(
  File "/opt/anaconda3/lib/python3.8/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/opt/anaconda3/lib/python3.8/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/opt/anaconda3/lib/python3.8/site-packages/httpx/_client.py", line 1681, in _send_single_request
    ) = await transport.handle_async_request(
  File "/opt/anaconda3/lib/python3.8/site-packages/httpx/_transports/default.py", line 283, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/opt/anaconda3/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 218, in handle_async_request
    await self._keepalive_sweep()
  File "/opt/anaconda3/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 303, in _keepalive_sweep
    now = await self._backend.time()
  File "/opt/anaconda3/lib/python3.8/site-packages/httpcore/_backends/auto.py", line 64, in time
    return await self.backend.time()
  File "/opt/anaconda3/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 198, in time
    return float(anyio.current_time())
TypeError: float() argument must be a string or a number, not 'coroutine'
```

**NOTE:** For me this issue appears only when running code from console. When running my app in Docker container it's all good.

**Comment by tomchristie** [comment]
Looks like you've got an out-of-date version of `anyio` installed there. (I think you've got version 2.x installed, while the latest versions of httpcore expect 3.x)

Not clear why that'd be occurring, since `httpcore` *does* pin to anyio 3.* in it's `setup.py`. Perhaps some manual installing/uninstalling of packages accidentally got things into a broken state.

You'd be able to resolve this by making sure that you update each of `httpx`, `httpcore`, `anyio` to the latest versions.
