### ISSUE TITLE
SOCKS5 proxy support only works with TLS websites

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#2053]
Confirmed and escalated https://github.com/encode/httpx/discussions/2052

<div type='discussions-op-text'>

<sup>Originally posted by **devl00p** January 27, 2022</sup>
Hello,

I was very exited to use the new socks support in httpx but it looks like it only works for https websites.

Script to reproduce :

1. Install and run Tor proxy locally
2. Setup Python environment with minimal dependencies ( `httpx[brotli, socks]==0.22.0"`)
3. Run the following Python script

```python
import httpx

for protocol in ("https", "http"):
    print(f"Testing with {protocol}")
    print("="*20)
    web = httpx.Client(proxies='socks5://127.0.0.1:9050/')
    response = web.get(f"{protocol}://httpbin.org/headers")
    print(response.text)
    print('')
```

What happens : 

```
Testing with https
====================
{
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Host": "httpbin.org", 
    "User-Agent": "python-httpx/0.22.0", 
    "X-Amzn-Trace-Id": "Root=1-61f30264-2b36ef696dddf32350f0ec0a"
  }
}


Testing with http
====================
Traceback (most recent call last):
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/backends/sync.py", line 52, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/lib64/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib64/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 244, in handle_request
    raise exc
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 228, in handle_request
    response = connection.handle_request(request)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/_sync/socks_proxy.py", line 285, in handle_request
    raise exc
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/_sync/socks_proxy.py", line 256, in handle_request
    stream = stream.start_tls(**kwargs)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    response = web.get(f"{protocol}://httpbin.org/headers")
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_client.py", line 1025, in get
    return self.request(
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/devloop/.local/share/virtualenvs/socks_test-a-xK_hEJ/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
```

It looks like even on insecure (not using TLS) websites, the client attempts to establish a TLS connection.

Expected behavior: getting the same response for http://httpbin.org/headers as for http**s**://httpbin.org/headers 

Python version: 3.8.12

Pip freeze output:
```
anyio==3.5.0
Brotli==1.0.9
certifi==2021.10.8
charset-normalizer==2.0.10
h11==0.12.0
httpcore==0.14.5
httpx==0.22.0
idna==3.3
rfc3986==1.5.0
sniffio==1.2.0
socksio==1.0.0
```

Keep up the good job

Regards</div>

**Comment by tomchristie** [comment]
Installed `pproxy`, and then started a proxy with...

```shell
$ pproxy 
Serving on :8080 by http,socks4,socks5 
```

HTTPS request via SOCKS proxy...

```shell
$ httpx --proxies socks5://127.0.0.1:8080/ https://httpbin.org/headers
HTTP/1.1 200 OK
Date: Fri, 28 Jan 2022 10:43:24 GMT
Content-Type: application/json
Content-Length: 226
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br",
        "Host": "httpbin.org",
        "User-Agent": "python-httpx/0.22.0",
        "X-Amzn-Trace-Id": "Root=1-61f3c8cc-001749354e8420320af481b9"
    }
}
```

But HTTP request via SOCKS proxy...

```shell
$ httpx --proxies socks5://127.0.0.1:8080/ http://httpbin.org/headers
ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)
```

Also, general note to folks - I tend to try to reduce a bug down to demo'ing it with the `httpx` cli - that'll generally ensure that you've got the *simplest possible* reproduction. Plus it's just got really low friction for other folks trying to replicate.

**Comment by tomchristie** [comment]
Resolved with [httpcore 0.14.6](https://github.com/encode/httpcore/blob/master/CHANGELOG.md#0146-february-1st-2022).
