### ISSUE TITLE
async client raises IPv4 or IPv6 address ValueError for URL "https://eodhistoricaldata.com"

### ISSUE THREAD

**Issue by topher-lo** [encode/httpx#2166]
### OS platform
- WSL Ubuntu 20.04
### Python version
- Python 3.9
### Dependencies
- Just httpx and asyncio

```python
import asyncio
import httpx

async def get():
  r = await httpx.get("https://eodhistoricaldata.com")
  print(r)

asyncio.run(get())
```
Causes the following error:
```
Traceback (most recent call last):
  File "/home/USER/miniconda3/envs/project/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 149, in connect_tcp
    addr_obj = ip_address(remote_host)
  File "/home/USER/miniconda3/envs/project/lib/python3.9/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'eodhistoricaldata.com' does not appear to be an IPv4 or IPv6 address
```

However using the synchronous client does not raise any error:
```
>>> import requests
>>> requests.get("https://eodhistoricaldata.com")
<Response [200]>
```

## Expected Behaviour
- <Response [200]> for both async and sync usage of httpx

**Comment by topher-lo** [comment]
Contacted the EOD Historical Data team and they suggested this (which works on my end)
```python
import asyncio
import httpx

async def get():
  r = await httpx.get("http://nonsecure.eodhistoricaldata.com/")
  print(r)

asyncio.run(get())
```
