### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AmericanY** [encode/httpx#2294]
```python
import trio
import httpx


async def worker(client, nurse):
    r = await client.head('https://google.com')
    nurse.cancel_scope.cancel()


async def main():
    async with httpx.AsyncClient(timeout=None) as client, trio.open_nursery() as nurse:
        for _ in range(3):
            nurse.start_soon(worker, client, nurse)


if __name__ == "__main__":
    trio.run(main)
```

```
Traceback (most recent call last):
  File "c:\Users\AmericaN\Desktop\Lab\test.py", line 17, in <module>
    trio.run(main)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\trio\_core\_run.py", line 1946, in 
run
    raise runner.main_task_outcome.error
  File "c:\Users\AmericaN\Desktop\Lab\test.py", line 11, in main
    async with httpx.AsyncClient(timeout=None) as client, trio.open_nursery() as nurse:
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_client.py", line 1997, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpx\_transports\default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpcore\_async\connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\httpcore\_async\connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 2 HTTP requests/responses were still in-flight.
```

**Comment by AmericanY** [comment]
https://github.com/encode/httpcore/blob/master/httpcore/_async/connection_pool.py#L277

**Comment by CatNeverCodes** [comment]
Try this
`async def worker(client, nurse):
    r = await client.get('https://www.baidu.com')


async def main():
    async with httpx.AsyncClient() as client, trio.open_nursery() as nurse:
        for _ in range(3):
            nurse.start_soon(worker, client, nurse)
    nurse.cancel_scope.cancel()`

**Comment by CatNeverCodes** [comment]
Try this.

python```
import trio
import httpx


async def worker(client):
    r = await client.get('https://www.baidu.com')
   


async def main():
    async with httpx.AsyncClient() as client, trio.open_nursery() as nurse:
        for _ in range(3):
            nurse.start_soon(worker, client)
    nurse.cancel_scope.cancel()


if __name__ == "__main__":
    trio.run(main)
```

I think it's due to cancel NurseryManager too early

**Comment by graingert** [comment]
This is a bug in httpcore where it tries to acquire a lock while in a cancelled scope. This should be refactored so no awaits happen inside the lock and so the lock can be removed.

**Comment by graingert** [comment]
https://github.com/encode/httpcore/issues/564

**Comment by graingert** [comment]
I'm closing this as it's a bug in httpcore

**Comment by novitae** [comment]
@AmericanY putting a custom Timeout worked for me
```python
async with AsyncClient(
    headers=video_headers,
     timeout=Timeout(timeout=10, connect=10, write=10, pool=10)
) as client:
```
(timeout from `httpx.Timeout`)
