### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gjmhmm8** [encode/httpx#2761]
Traceback (most recent call last):
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\h2\connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.SEND_HEADERS: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\Users\gjmhmm8\Desktop\gua\test3.py", line 65, in get_chapters
    res = await client.get(url, headers=headers, cookies=cookies, timeout=60)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1740, in get
    return await self.request(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1494, in request
    response = await self.send(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http2.py", line 165, in handle_async_request
    return await h2_stream.handle_async_request(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http2.py", line 339, in handle_async_request
    await self.send_headers(method, url, headers, has_body, timeout)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http2.py", line 398, in send_headers
    await self.connection.send_headers(self.stream_id, headers, end_stream, timeout)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\http2.py", line 271, in send_headers
    self._h2_state.send_headers(stream_id, headers, end_stream=end_stream)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\h2\connection.py", line 766, in send_headers
    self.state_machine.process_input(ConnectionInputs.SEND_HEADERS)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\h2\connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D07472E280>
Traceback (most recent call last):
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by zanieb** [comment]
@gjmhmm8 Hi, this is fixed in the latest `httpcore` version (a dependency of this library). Use `pip install --upgrade httpcore` and you should be good. See https://github.com/encode/httpx/discussions/2112 for details.

In the future, please open a [Discussion](https://github.com/encode/httpx/discussions) instead of an issue.
