### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gjmhmm8** [encode/httpx#2762]
Traceback (most recent call last):
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\Users\gjmhmm8\Desktop\gua\test3.py", line 67, in get_chapters
    res = await client.get(url, headers=headers, cookies=cookies, timeout=60)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\gjmhmm8\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.WriteError

**Comment by zanieb** [comment]
Hi as I mentioned in your report at https://github.com/encode/httpx/issues/2761 we use discussions as a starting point for bug reports. 

Additionally, please use a descriptive title and provide a **small** example that can be used to reproduce the issue.
