### ISSUE TITLE
Gunicorn worker fails to boot due to NotImplementedError 

### ISSUE THREAD

**Issue by codebanesr** [encode/httpx#3099]
**Description:**
I'm encountering a `NotImplementedError: unsupported platform` which causes my Gunicorn worker process to fail. This seems to be originating from the httpx/trio libraries.  Has anyone else experienced similar issues?  

**Error Traceback:**
```
[2024-02-18 21:08:17 -0800] [42822] [ERROR] Exception in worker process
Traceback (most recent call last):
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
  worker.init_process()
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
  super().init_process()
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
  self.load_wsgi()
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
  self.wsgi = self.app.wsgi()
        ^^^^^^^^^^^^^^^
  ... (Remainder of traceback) 
NotImplementedError: unsupported platform
```

**Environment:**
* **OS:**  Mac M2 [darwin]
* **Python:**  3.11.7
* **Gunicorn:**  version 21.2.0
* **httpx:**  Version (output of `pip show httpx`)
```
Name: httpx
Version: 0.25.0
Summary: The next generation HTTP client.
Home-page: 
Author: 
Author-email: Tom Christie <tom@tomchristie.com>
License: 
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: certifi, httpcore, idna, sniffio
Required-by: anthropic, gotrue, openai, postgrest, qdrant-client, storage3, supabase, supafunc
```

* **trio:** Version (output of `pip show trio`)
```
Name: trio
Version: 0.23.1
Summary: A friendly Python library for async concurrency and I/O
Home-page: https://github.com/python-trio/trio
Author: Nathaniel J. Smith
Author-email: njs@pobox.com
License: MIT OR Apache-2.0
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: attrs, idna, outcome, sniffio, sortedcontainers
Required-by: selenium, trio-websocket
```

Let me know if any more details are necessary. 

This is a dependency for `qdrant_client` that uses trio, that then uses httpx

**Comment by tomchristie** [comment]
There's no mention of `httpx` (or `trio`) in the traceback you've shown?
