### ISSUE TITLE
Httpx failing on verify certificate

### ISSUE THREAD

**Issue by GnubiBORED** [encode/httpx#430]
Im opening again cause its still happening to me
Releated #376

Im using httpx 0.7.4
and charlesproxy: https://www.charlesproxy.com/

```
import httpx
client = httpx.Client(proxies={
    "http": "http://192.168.1.78:8888",
    "https": "http://192.168.1.78:8888",

})
headers = {}
client_cer = r'C:\Users\localhost\Documents\Enrique\123.pem'

request = client.get("http://whoer.net",headers=headers,verify=client_cer)
```

```
C:\Users\localhost\PycharmProjects\TribalW_Test_Env\Basic\tests\httpx>set HTTPX_DEBUG=1

C:\Users\localhost\PycharmProjects\TribalW_Test_Env\Basic\tests\httpx>python proxy_test.py
22:50:14.296 - httpx.dispatch.proxy_http - forward_connection proxy_url=URL('http://192.168.1.78:8888') origin=Origin(scheme='http' host='192.168.1.78' port=8888)
22:50:14.296 - httpx.dispatch.connection_pool - acquire_connection origin=Origin(scheme='http' host='192.168.1.78' port=8888)
22:50:14.298 - httpx.dispatch.connection_pool - new_connection connection=HTTPConnection(origin=Origin(scheme='http' host='192.168.1.78' port=8888))
22:50:14.298 - httpx.dispatch.connection - start_connect host='192.168.1.78' port=8888 timeout=TimeoutConfig(timeout=5.0)
22:50:14.299 - httpx.dispatch.connection - connected http_version='HTTP/1.1'
22:50:14.300 - httpx.dispatch.http11 - send_headers method='GET' target='http://whoer.net' headers=Headers({'host': 'whoer.net', 'user-agent': 'python-httpx/0.7.4', 'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'connection': 'keep-alive'})
22:50:14.301 - httpx.dispatch.http11 - receive_event event=NEED_DATA
22:50:14.332 - httpx.dispatch.http11 - receive_event event=Response(status_code=301, headers=[(b'date', b'Wed, 02 Oct 2019 20:50:15 GMT'), (b'transfer-encoding', b'chunked'), (b'cache-control', b'max-age=3600'), (b'expires', b'Wed, 02 Oct 2019 21:50:15 GMT'), (b'location', b'https://whoer.net/'), (b'vary', b'Accept-Encoding'), (b'server', b'cloudflare'), (b'cf-ray', b'51f98c30ed2ed685-MAD'), (b'connection', b'keep-alive')], http_version=b'1.1', reason=b'Moved Permanently')
22:50:14.333 - httpx.dispatch.proxy_http - tunnel_connection proxy_url=URL('http://192.168.1.78:8888') origin=Origin(scheme='https' host='whoer.net' port=443)
22:50:14.334 - httpx.dispatch.connection - start_connect host='192.168.1.78' port=8888 timeout=TimeoutConfig(timeout=5.0)
22:50:14.335 - httpx.dispatch.connection - connected http_version='HTTP/1.1'
22:50:14.335 - httpx.dispatch.http11 - send_headers method='CONNECT' target='whoer.net:443' headers=Headers({'host': '192.168.1.78:8888', 'user-agent': 'python-httpx/0.7.4', 'accept-encoding': 'gzip, deflate, br', 'connection': 'keep-alive', 'accept': '*/*'})
22:50:14.335 - httpx.dispatch.http11 - receive_event event=NEED_DATA
22:50:14.348 - httpx.dispatch.http11 - receive_event event=Response(status_code=200, headers=[], http_version=b'1.1', reason=b'Connection established')
22:50:14.348 - httpx.dispatch.proxy_http - tunnel_response proxy_url=URL('http://192.168.1.78:8888') origin=Origin(scheme='https' host='whoer.net' port=443) response=<Response [200 OK]>
22:50:14.349 - httpx.dispatch.http11 - receive_event event=PAUSED
22:50:14.352 - httpx.config - load_ssl_context verify=True cert=None trust_env=None http_versions=HTTPVersionConfig(['HTTP/1.1'])
22:50:14.353 - httpx.config - load_verify_locations cafile=C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\certifi\cacert.pem
22:50:14.368 - httpx.dispatch.proxy_http - tunnel_start_tls proxy_url=URL('http://192.168.1.78:8888') origin=Origin(scheme='https' host='whoer.net' port=443)
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018EAE7FB3C8>
transport: <_SelectorSocketTransport fd=672 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018EAE7FB3C8>
transport: <_SelectorSocketTransport closing fd=672 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
Traceback (most recent call last):
  File "proxy_test.py", line 11, in <module>
    request = client.get("http://whoer.net",headers=headers,verify=client_cer)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 820, in get
    trust_env=trust_env,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 735, in request
    trust_env=trust_env,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 764, in send
    async_response = concurrency_backend.run(coroutine, *args, **kwargs)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\concurrency\asyncio.py", line 261, in run
    return self.loop.run_until_complete(coroutine(*args, **kwargs))
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 255, in _get_response
    return await get_response(request)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\middleware\redirect.py", line 41, in __call__
    return await self(next_request, get_response)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\middleware\redirect.py", line 31, in __call__
    response = await get_response(request)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 216, in get_response
    request, verify=verify, cert=cert, timeout=timeout
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 248, in send
    request=request, verify=verify, cert=cert, timeout=timeout
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\connection_pool.py", line 118, in send
    connection = await self.acquire_connection(origin=request.url.origin)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 97, in acquire_connection
    return await self.tunnel_connection(origin)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 115, in tunnel_connection
    await self.tunnel_start_tls(origin, connection)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 199, in tunnel_start_tls
    timeout=timeout,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\concurrency\asyncio.py", line 236, in start_tls
    timeout=timeout.connect_timeout,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1134, in start_tls
    await waiter
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

```

**Comment by sethmlarson** [comment]
Thanks for opening, I'll have to fire up the proxy again and try it.

**Comment by sethmlarson** [comment]
I'm unable to reproduce your issue, I did the following:

- Start Charles proxy running on port 8888
- Export the certificate to `/tmp/charles.pem with `Help > SSL Proxying > Save Charles Root Certificate...`
- Add `www.google.com, 443` to the `Tools > SSL Proxying Settings` menu
- Use the following code in Python 3.8:

```python
>>> import httpx
>>> client = httpx.Client(proxies="http://127.0.0.1:8888", verify="/tmp/charles.pem")
>>> client.request("GET", "https://www.google.com")
16:54:20.103 - httpx.dispatch.proxy_http - tunnel_connection proxy_url=URL('http://127.0.0.1:8888') origin=Origin(scheme='https' host='www.google.com' port=443)
16:54:20.105 - httpx.dispatch.connection - start_connect host='127.0.0.1' port=8888 timeout=TimeoutConfig(timeout=5.0)
16:54:20.107 - httpx.dispatch.connection - connected http_version='HTTP/1.1'
16:54:20.108 - httpx.dispatch.http11 - send_headers method='CONNECT' target='www.google.com:443' headers=Headers({'host': '127.0.0.1:8888', 'user-agent': 'python-httpx/0.7.4', 'accept-encoding': 'gzip, deflate, br', 'connection': 'keep-alive', 'accept': '*/*'})
16:54:20.109 - httpx.dispatch.http11 - receive_event event=NEED_DATA
16:54:20.147 - httpx.dispatch.http11 - receive_event event=Response(status_code=200, headers=[], http_version=b'1.1', reason=b'Connection established')
16:54:20.148 - httpx.dispatch.proxy_http - tunnel_response proxy_url=URL('http://127.0.0.1:8888') origin=Origin(scheme='https' host='www.google.com' port=443) response=<Response [200 OK]>
16:54:20.148 - httpx.dispatch.http11 - receive_event event=PAUSED
16:54:20.152 - httpx.config - load_ssl_context verify='/tmp/charles.pem' cert=None trust_env=None http_versions=HTTPVersionConfig(['HTTP/1.1'])
16:54:20.156 - httpx.config - load_verify_locations cafile=/tmp/charles.pem
16:54:20.157 - httpx.dispatch.proxy_http - tunnel_start_tls proxy_url=URL('http://127.0.0.1:8888') origin=Origin(scheme='https' host='www.google.com' port=443)
16:54:20.359 - httpx.dispatch.proxy_http - tunnel_tls_complete proxy_url=URL('http://127.0.0.1:8888') origin=Origin(scheme='https' host='www.google.com' port=443) http_version='HTTP/1.1'
16:54:20.359 - httpx.dispatch.http11 - send_headers method='GET' target='/' headers=Headers({'host': 'www.google.com', 'user-agent': 'python-httpx/0.7.4', 'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'connection': 'keep-alive'})
16:54:20.359 - httpx.dispatch.http11 - receive_event event=NEED_DATA
16:54:20.461 - httpx.dispatch.http11 - receive_event event=Response(status_code=200, headers=[(b'date', b'Thu, 03 Oct 2019 21:54:20 GMT'), (b'expires', b'-1'), (b'cache-control', b'private, max-age=0'), (b'content-type', b'text/html; charset=ISO-8859-1'), (b'p3p', b'CP="This is not a P3P policy! See g.co/p3phelp for more info."'), (b'content-encoding', b'gzip'), (b'server', b'gws'), (b'x-xss-protection', b'0'), (b'x-frame-options', b'SAMEORIGIN'), (b'set-cookie', b'1P_JAR=2019-10-03-21; expires=Sat, 02-Nov-2019 21:54:20 GMT; path=/; domain=.google.com; SameSite=none'), (b'set-cookie', b'NID=188=gWHLbZnzdygZng9-oGB88EqKgPjlruPn1_B0Q_etsG8hbEc9WtaZODQ3qKMFOmsCXBHQU9-xUkAgvqUhBiwogz4_gU5w-vVbq9qE0BUTBAnQQzEkXFOTsPiHVUpoYFirPJgNxgqOAkETMdPgQO8yNU9J85xBXilX4bsn0UuUseM; expires=Fri, 03-Apr-2020 21:54:20 GMT; path=/; domain=.google.com; HttpOnly'), (b'alt-svc', b'quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000'), (b'transfer-encoding', b'chunked'), (b'connection', b'keep-alive')], http_version=b'1.1', reason=b'OK')
16:54:20.461 - httpx.dispatch.http11 - receive_event event=NEED_DATA
16:54:20.503 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.504 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.504 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.504 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.504 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.505 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.505 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.505 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.505 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.506 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.506 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.507 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.507 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.507 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.507 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.508 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.508 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.508 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.508 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.508 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.509 - httpx.dispatch.http11 - receive_event event=Data(<1 bytes>)
16:54:20.509 - httpx.dispatch.http11 - receive_event event=Data(<272 bytes>)
16:54:20.509 - httpx.dispatch.http11 - receive_event event=Data(<1389 bytes>)
16:54:20.509 - httpx.dispatch.http11 - receive_event event=Data(<1389 bytes>)
16:54:20.510 - httpx.dispatch.http11 - receive_event event=Data(<894 bytes>)
16:54:20.510 - httpx.dispatch.http11 - receive_event event=NEED_DATA
16:54:20.510 - httpx.dispatch.http11 - receive_event event=Data(<495 bytes>)
16:54:20.511 - httpx.dispatch.http11 - receive_event event=Data(<649 bytes>)
16:54:20.511 - httpx.dispatch.http11 - receive_event event=EndOfMessage(headers=[])
16:54:20.511 - httpx.dispatch.http11 - response_closed our_state=DONE their_state=DONE
16:54:20.511 - httpx.dispatch.connection_pool - release_connection connection=HTTPConnection(origin=Origin(scheme='https' host='www.google.com' port=443))
<Response [200 OK]>
```

Do any of the above steps not match what you're doing?

**Comment by GnubiBORED** [comment]
Yeah okay , my u
