### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by GnubiBORED** [encode/httpx#475]
So unless im doing something bad, i doubt cause i just copied the code in #469

> 
> 
> So the way I'd recommend accomplishing this:
> 
> ```python
> >>> import ssl
> >>> import httpx
> >>> ssl_config = httpx.SSLConfig()
> >>> ssl_context = ssl_config.load_ssl_context()
> >>> ssl_context.options |= getattr(ssl, "OP_NO_TLSv1_3", 0)
> >>> client = httpx.Client(verify=ssl_context)
> >>> resp = client.get("https://howsmyssl.com/a/check")
> >>> print(resp.json()["tls_version"])
> 'TLSv1.2'
> ```
> 
> Currently we don't allow passing an `SSLConfig` object to `verify=` (which maybe we should because this is painful)

my code:

```
import httpx
import json
import ssl
import collections
import traceback
class test_client():
    def start(self, headers_pass, body_pass, params, url, ip, method, cookies):

        ssl_config = httpx.SSLConfig()

        ssl_context = ssl_config.load_ssl_context()

        ssl_context.options |= getattr(ssl, "OP_NO_TLSv1_3", 0)

        ssl_context.load_verify_locations(r'C:\Users\localhost\Documents\XXXX\charlesproxy.pem')
        try:
        
            headers = collections.OrderedDict(headers_pass)
        
            if '127.0.0.1' not in ip:
              
                proxy = httpx.HTTPProxy(
                    
                    "http://{}".format(ip),

                    proxy_headers={"Host": url+':443',
                                   "Proxy-Connection":"Keep-Alive"}
                )

                client = httpx.Client(proxies={
                    "http": proxy,
                    "https": proxy




                },verify=ssl_context)
            else:

                client = httpx.Client(verify=ssl_context)



            if method == 'get':

                response = client.get(url,headers= collections.OrderedDict(headers_pass),params=params)
                    return json_data


            elif method == 'post':

                        body = str(body_pass)
                        response = client.post(url, 
headers=collections.OrderedDict(headers_pass),params=params,data=body)
                        json_data = json.loads(response)
                        return json_data

        except Exception as e:
            print(e.args)
            print(traceback.print_exc())

```

error:

```
(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001C570342160>
transport: <_SelectorSocketTransport fd=992 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001C570342160>
transport: <_SelectorSocketTransport closing fd=992 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
Traceback (most recent call last):
  File "C:\Users\localhost\PycharmProjects\TribalW_Test_Env\Basic\network\client\httpx_test1.py", line 81, in start
    response = client.post(url, headers=collections.OrderedDict(headers_pass),params=params,data=body)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 916, in post
    trust_env=trust_env,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 735, in request
    trust_env=trust_env,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 764, in send
    async_response = concurrency_backend.run(coroutine, *args, **kwargs)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\concurrency\asyncio.py", line 261, in run
    return self.loop.run_until_complete(coroutine(*args, **kwargs))
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 255, in _get_response
    return await get_response(request)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\middleware\redirect.py", line 31, in __call__
    response = await get_response(request)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\client.py", line 216, in get_response
    request, verify=verify, cert=cert, timeout=timeout
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 248, in send
    request=request, verify=verify, cert=cert, timeout=timeout
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\connection_pool.py", line 118, in send
    connection = await self.acquire_connection(origin=request.url.origin)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 97, in acquire_connection
    return await self.tunnel_connection(origin)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 115, in tunnel_connection
    await self.tunnel_start_tls(origin, connection)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\dispatch\proxy_http.py", line 199, in tunnel_start_tls
    timeout=timeout,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\concurrency\asyncio.py", line 236, in start_tls
    timeout=timeout.connect_timeout,
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1134, in start_tls
    await waiter
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\localhost\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
```

**Comment by florimondmanca** [comment]
@GnubiBORED The snippet from #469 works well on my side:

```python
import ssl
import httpx
ssl_config = httpx.SSLConfig()
ssl_context = ssl_config.load_ssl_context()
ssl_context.options |= ssl.OP_NO_TLSv1_3
resp = httpx.get("https://howsmyssl.com/a/check", verify=ssl_context)
tls_version = resp.json()["tls_version"]
assert tls_version == "TLS 1.2"
```

It seems the issue you're having is that CharlesProxy certificates are not trusted on your machine. I found documentation on how to enable this in the CharlesProxy docs, [here](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/). Closing as non-HTTPX-related. :-)

**Comment by GnubiBORED** [comment]
sorry @florimondmanca but i do think its a httpx issue cause if i pass the certificate in a normal way, it works good but when im doing with 
`ssl_config = httpx.SSLConfig()
ssl_context = ssl_config.load_ssl_context()`
isnt working properly, if @sethmlarson can try with charlesproxy to figure out, cause for me isnt working as if i pass inside client
`>>> client = httpx.Client(proxies={"http": "http://127.0.0.1:8888", "https": "http://127.0.0.1:8888"}, verify="/tmp/charles.pem")`
