### ISSUE TITLE
Tests fail with `TypeError: attrib() got an unexpected keyword argument 'eq'`

### ISSUE THREAD

**Issue by gdhameeja** [encode/httpx#549]
When running nox, the build fails for python 3.7. However, it passes for python 3.6.x.
Here is the full traceback:
```
================================================================== 490 passed, 1 skipped, 1 xfailed in 11.22s ==================================================================
nox > Session test-3.6 was successful.
nox > Running session test-3.7
nox > Re-using existing virtual environment at .nox/test-3-7.
nox > pip install --upgrade -r test-requirements.txt
nox > python -m pytest
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pytest.py", line 101, in <module>
    raise SystemExit(pytest.main())
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 72, in main
    config = _prepareconfig(args, plugins)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 223, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 742, in pytest_cmdline_parse
    self.parse(args)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 948, in parse
    self._preparse(args, addopts=addopts)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/config/__init__.py", line 896, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pluggy/manager.py", line 297, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 92, in load
    module = import_module(match.group('module'))
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pytest_trio/__init__.py", line 4, in <module>
    from .plugin import trio_fixture
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/pytest_trio/plugin.py", line 8, in <module>
    import trio
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/trio/_core/__init__.py", line 19, in <module>
    from ._run import (
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/trio/_core/_run.py", line 22, in <module>
    from outcome import Error, Value, capture
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/outcome/__init__.py", line 11, in <module>
    from ._async import Error, Outcome, Value, acapture, capture
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/outcome/_async.py", line 3, in <module>
    from ._sync import Error as ErrorBase
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/outcome/_sync.py", line 28, in <module>
    class Outcome(ABC):
  File "/home/melvault/Documents/programs/opensource/httpx/.nox/test-3-7/lib/python3.7/site-packages/outcome/_sync.py", line 43, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'
```
Here is my `pip freeze` output:
```
argcomplete==1.10.2
async-generator==1.10
attrs==19.3.0
brotlipy==0.7.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
Click==7.0
colorlog==4.0.2
contextvars==2.4
coverage==4.5.4
cryptography==2.8
entrypoints==0.3
flake8==3.7.9
flake8-bugbear==19.8.0
flake8-pie==0.4.2
h11==0.8.1
h2==3.1.1
hpack==3.0.0
hstspreload==2019.11.22
httptools==0.0.13
-e git+https://github.com/gdhameeja/httpx.git@4aeef6384b40db3720470a0340a26134c1cb870d#egg=httpx
hyperframe==5.2.0
idna==2.8
immutables==0.11
importlib-metadata==0.23
isort==4.3.21
mccabe==0.6.1
more-itertools==7.2.0
mypy==0.740
mypy-extensions==0.4.3
nox==2019.11.9
outcome==1.0.1
packaging==19.2
pkg-resources==0.0.0
pluggy==0.13.1
py==1.8.0
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
pyparsing==2.4.5
pytest==5.3.0
pytest-asyncio==0.10.0
pytest-cov==2.8.1
pytest-trio==0.5.2
rfc3986==1.3.2
six==1.13.0
sniffio==1.1.0
sortedcontainers==2.1.0
trio==0.13.0
trustme==0.5.3
typed-ast==1.4.0
typing-extensions==3.7.4.1
uvicorn==0.10.8
uvloop==0.14.0
virtualenv==16.7.8
wcwidth==0.1.7
websockets==8.1
zipp==0.6.0
```

**Comment by yeraydiazdiaz** [comment]
Hi @gdhameeja, I can't reproduce this on master. I suggest removing the `.nox` directory as it's possible the virtualenv needs to be updated.
