### ISSUE TITLE
On (sync) httpx.Client, using the "proxies" parameter does not work

### ISSUE THREAD

**Issue by fbexiga** [encode/httpx#770]
When doing something like this

```
proxy = {
     'http' : 'http://X.X.X.X:YY',
     'https' : 'http://X.X.X.X:YY'
}

def run_sync(url):
    with httpx.Client(verify=False, proxies=proxy) as client:
        response = client.get(url)
```

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    run_sync(url)
  File "test.py", line 10, in run_sync
    with httpx.Client(verify=False, proxies=proxy) as client:
  File ".../lib/python3.6/site-packages/httpx/client.py", line 479, in __init__
    for key, proxy in proxy_map.items()
  File "../lib/python3.6/site-packages/httpx/client.py", line 479, in <dictcomp>
    for key, proxy in proxy_map.items()
  File "../lib/python3.6/site-packages/httpx/client.py", line 514, in init_proxy_dispatch
    trust_env=trust_env,
  File "../lib/python3.6/site-packages/httpx/dispatch/urllib3.py", line 60, in __init__
    block=block,
  File "../lib/python3.6/site-packages/httpx/dispatch/urllib3.py", line 85, in init_pool_manager
    block=block,
  File "../lib/python3.6/site-packages/urllib3/poolmanager.py", line 414, in __init__
    proxy = parse_url(proxy_url)
  File "../lib/python3.6/site-packages/urllib3/util/url.py", line 363, in parse_url
    if not SCHEME_RE.search(url):
TypeError: expected string or bytes-like object
```

By editing the urllib3 parse_url function to print the type of the url variable, we get `<class 'httpx.models.URL'>` which should be `<class 'str'>` for it to work correctly.

There is an additional issue with the urllib3 calls. For a private proxy that includes authentication, assuming the above error is fixed, the request will fail with a "Proxy Authentication Required" error. I think httpx is doing this:

```
>>> from urllib3 import ProxyManager
>>> proxy = urllib3.ProxyManager('http://user:pass@x.x.x.x:yy')
>>> x = proxy.request('GET', 'http://google.com/')
>>> x.status
407
```

instead of this

```
>>> from urllib3 import ProxyManager, make_headers
>>> default_headers = make_headers(proxy_basic_auth='user:pass')
>>> proxy = urllib3.ProxyManager('http://x.x.x.x:yy', headers=default_headers)
>>> x = proxy.request('GET', 'http://google.com/')
>>> x.status
200
```

**Comment by tomchristie** [comment]
Indeed. Closed in #763 - we ought to cut a release.
