### ISSUE TITLE
Where is SSLConfig?

### ISSUE THREAD

**Issue by GnubiBORED** [encode/httpx#904]
I ve been around 4 months witouth using HTTPX i installed again recently but my old code isnt working
```

        ssl_config = httpx.SSLConfig()

        ssl_context = ssl_config.load_ssl_context()

        ssl_context.options |= getattr(ssl, "OP_NO_TLSv1_3", 0)

        ssl_context.load_verify_locations(path)
```

im getting
```
ssl_config = httpx.SSLConfig()
AttributeError: module 'httpx' has no attribute 'SSLConfig'

```

**Comment by dalf** [comment]
Since #785 SSLConfig has been moved to ```httpx._config.SSLConfig``` (a private package).

```python
import httpx
import httpx._config
import httpcore

ssl_config = httpx._config.SSLConfig(...)
ssl_context = ssl_config.load_ssl_context()
dispatch = httpcore.AsyncConnectionPool(
            ssl_context=ssl_context,
            max_keepalive=httpx._config.DEFAULT_POOL_LIMITS.soft_limit,
            max_connections=httpx._config.DEFAULT_POOL_LIMITS.hard_limit,
            http2=http2,
)
client = httpx.AsyncClient(dispatch=dispatch)
```

**Comment by GnubiBORED** [comment]
@dalf 


```
C:\Users\localhost\AppData\Local\Programs\Python\Python37\python.exe C:/Users/localhost/PycharmProjects/HTTP_BOT/httpx/llamadas_http.py
Traceback (most recent call last):
  File "C:/Users/localhost/PycharmProjects/HTTP_BOT/httpx/llamadas_http.py", line 2, in <module>
    from httpx.Client import http_Client
  File "C:\Users\localhost\PycharmProjects\HTTP_BOT\httpx\Client.py", line 6, in <module>
    import httpx._config
ModuleNotFoundError: No module named 'httpx._config'


```


code:
`import httpx._config
    ssl_config = httpx._config.SSLConfig()

        ssl_context = ssl_config.load_ssl_context()`

Im using version httpx 0.12.1

**Comment by GnubiBORED** [comment]
solved
