### ISSUE TITLE
BoundedSemaphore error when using proxies with async client

### ISSUE THREAD

**Issue by yeraydiazdiaz** [encode/httpx#922]
### Checklist

- [*] The bug is reproducible against the latest release and/or `master`.
- [*] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When using a proxy with the `AsyncClient` the request completes correctly but on `__aexit__` a `BoundedSemaphore` error is raised.

### To reproduce

With a proxy server running on port 8080:

```python
import asyncio
import httpx

proxies = {"http": "http://127.0.0.1:8080/"}


async def request():
    async with httpx.AsyncClient(proxies=proxies) as client:
        response = await client.get("http://example.org")
        assert response.status_code == 200


asyncio.run(request())
```

### Expected behavior

No exception is raised.

### Actual behavior

An exception is raised with the following traceback

```
✗ HTTPX_LOG_LEVEL=debug python .dev/bounded_semaphore_error.py
DEBUG [2020-05-02 11:30:17] httpx._client - HTTP Request: GET http://example.org "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File ".dev/bounded_semaphore_error.py", line 13, in <module>
    asyncio.run(request())
  File "/Users/yeray/.pyenv/versions/3.8.1/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/yeray/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File ".dev/bounded_semaphore_error.py", line 10, in request
    assert response.status_code == 200
  File "/Users/yeray/code/personal/_forks/httpx/httpx/_client.py", line 1449, in __aexit__
    await self.aclose()
  File "/Users/yeray/code/personal/_forks/httpx/httpx/_client.py", line 1438, in aclose
    await proxy.aclose()
  File "/Users/yeray/.pyenv/versions/httpcore/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 274, in aclose
    await self._remove_from_pool(connection)
  File "/Users/yeray/.pyenv/versions/httpcore/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 257, in _remove_from_pool
    self._connection_semaphore.release()
  File "/Users/yeray/.pyenv/versions/httpcore/lib/python3.8/site-packages/httpcore/_backends/asyncio.py", line 208, in release
    self.semaphore.release()
  File "/Users/yeray/.pyenv/versions/3.8.1/lib/python3.8/asyncio/locks.py", line 533, in release
    raise ValueError('BoundedSemaphore released too many times')
ValueError: BoundedSemaphore released too many times
```

### Environment

- OS: MacOS
- Python version: 3.8.1
- HTTPX version: 3b9ebe0 (effectively 0.13.0dev)
- Async environment: asyncio
- HTTP proxy: Yes
- Custom certificates: No

**Comment by yeraydiazdiaz** [comment]
I found the root cause in `httpcore` opening a PR there.
